linters:
  disable:
    - structcheck
    - unused
    - typecheck # disabled because not working with swig
    - deadcode # disabled because not working with swig
  enable:
    - lll
    - revive
    - gofmt
    - gci
    #- gosec
run:
  skip-dirs:
    - primitives/curve25519/myref10
issues:
  exclude-rules:
    - path: primitives/vss
      text: "illegal character U\\+0023 '#'" # fix issue with swig
linters-settings:
  govet:
    disable:
      - cgocall # disabled because not working with swig
  revive:
    ignore-generated-header: false
    severity: warning
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: line-length-limit
        arguments: [ 120 ]