on: [push, pull_request]
name: Build and Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install libsodium # see https://stackoverflow.com/a/57948488/2945326
        # Note that we copy-paste this script in both lint.yml and test.yml
        # because "act" does not support composite actions
        # https://github.com/nektos/act/issues/339
        run:   |
          if [ "$RUNNER_OS" == "Linux" ]; then
               sudo apt-get install -y libsodium-dev
          elif [ "$RUNNER_OS" == "macOS" ]; then
               brew install libsodium
          else
               echo "$RUNNER_OS not supported"
               exit 1
          fi
        shell: bash
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: make test