// #nosec
//go:build go1.6
// +build go1.6

// Code generated by codecgen - DO NOT EDIT.

package auditor

import (
	"errors"
	pkg1_curve25519 "github.com/shaih/go-yosovss/primitives/curve25519"
	codec1978 "github.com/ugorji/go/codec"
	"runtime"
	"strconv"
)

const (
	// ----- content types ----
	codecSelferCcUTF88453 = 1
	codecSelferCcRAW8453  = 255
	// ----- value types used ----
	codecSelferValueTypeArray8453     = 10
	codecSelferValueTypeMap8453       = 9
	codecSelferValueTypeString8453    = 6
	codecSelferValueTypeInt8453       = 2
	codecSelferValueTypeUint8453      = 3
	codecSelferValueTypeFloat8453     = 4
	codecSelferValueTypeNil8453       = 1
	codecSelferBitsize8453            = uint8(32 << (^uint(0) >> 63))
	codecSelferDecContainerLenNil8453 = -2147483648
)

var (
	errCodecSelferOnlyMapOrArrayEncodeToStruct8453 = errors.New(`only encoded map or array can be decoded into a struct`)
)

type codecSelfer8453 struct{}

func codecSelfer8453False() bool { return false }
func codecSelfer8453True() bool  { return true }

func init() {
	if codec1978.GenVersion != 25 {
		_, file, _, _ := runtime.Caller(0)
		ver := strconv.FormatInt(int64(codec1978.GenVersion), 10)
		panic(errors.New("codecgen version mismatch: current: 25, need " + ver + ". Re-generate file: " + file))
	}
	if false { // reference the types, but skip this branch at build/run time
		var _ pkg1_curve25519.PointXY
	}
}

func (DLStatement) codecSelferViaCodecgen() {}
func (x *DLStatement) CodecEncodeSelf(e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if z.EncBasicHandle().CheckCircularRef {
		z.EncEncode(x)
		return
	}
	if x == nil {
		r.EncodeNil()
	} else {
		yy2arr2 := z.EncBasicHandle().StructToArray
		_ = yy2arr2
		const yyr2 bool = false // struct tag has 'toArray'
		if yyr2 || yy2arr2 {
			z.EncWriteArrayStart(2)
			z.EncWriteArrayElem()
			if x.G == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.G), e)
			} // end block: if x.G slice == nil
			z.EncWriteArrayElem()
			if x.X == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.X), e)
			} // end block: if x.X slice == nil
			z.EncWriteArrayEnd()
		} else {
			z.EncWriteMapStart(2)
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"G\"")
			} else {
				r.EncodeString(`G`)
			}
			z.EncWriteMapElemValue()
			if x.G == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.G), e)
			} // end block: if x.G slice == nil
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"X\"")
			} else {
				r.EncodeString(`X`)
			}
			z.EncWriteMapElemValue()
			if x.X == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.X), e)
			} // end block: if x.X slice == nil
			z.EncWriteMapEnd()
		}
	}
}

func (x *DLStatement) CodecDecodeSelf(d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	yyct2 := r.ContainerType()
	if yyct2 == codecSelferValueTypeNil8453 {
		*(x) = DLStatement{}
	} else if yyct2 == codecSelferValueTypeMap8453 {
		yyl2 := z.DecReadMapStart()
		if yyl2 == 0 {
		} else {
			x.codecDecodeSelfFromMap(yyl2, d)
		}
		z.DecReadMapEnd()
	} else if yyct2 == codecSelferValueTypeArray8453 {
		yyl2 := z.DecReadArrayStart()
		if yyl2 != 0 {
			x.codecDecodeSelfFromArray(yyl2, d)
		}
		z.DecReadArrayEnd()
	} else {
		panic(errCodecSelferOnlyMapOrArrayEncodeToStruct8453)
	}
}

func (x *DLStatement) codecDecodeSelfFromMap(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyhl3 bool = l >= 0
	for yyj3 := 0; ; yyj3++ {
		if yyhl3 {
			if yyj3 >= l {
				break
			}
		} else {
			if z.DecCheckBreak() {
				break
			}
		}
		z.DecReadMapElemKey()
		yys3 := r.DecodeStringAsBytes()
		z.DecReadMapElemValue()
		switch string(yys3) {
		case "G":
			h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.G), d)
		case "X":
			h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.X), d)
		default:
			z.DecStructFieldNotFound(-1, string(yys3))
		} // end switch yys3
	} // end for yyj3
}

func (x *DLStatement) codecDecodeSelfFromArray(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyj8 int
	var yyb8 bool
	var yyhl8 bool = l >= 0
	yyj8++
	if yyhl8 {
		yyb8 = yyj8 > l
	} else {
		yyb8 = z.DecCheckBreak()
	}
	if yyb8 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.G), d)
	yyj8++
	if yyhl8 {
		yyb8 = yyj8 > l
	} else {
		yyb8 = z.DecCheckBreak()
	}
	if yyb8 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.X), d)
	for {
		yyj8++
		if yyhl8 {
			yyb8 = yyj8 > l
		} else {
			yyb8 = z.DecCheckBreak()
		}
		if yyb8 {
			break
		}
		z.DecReadArrayElem()
		z.DecStructFieldNotFound(yyj8-1, "")
	}
}

func (x *DLStatement) IsCodecEmpty() bool {
	return !(len(x.G) != 0 || len(x.X) != 0 || false)
}

func (DLWitness) codecSelferViaCodecgen() {}
func (x *DLWitness) CodecEncodeSelf(e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if z.EncBasicHandle().CheckCircularRef {
		z.EncEncode(x)
		return
	}
	if x == nil {
		r.EncodeNil()
	} else {
		yy2arr2 := z.EncBasicHandle().StructToArray
		_ = yy2arr2
		const yyr2 bool = false // struct tag has 'toArray'
		if yyr2 || yy2arr2 {
			z.EncWriteArrayStart(1)
			z.EncWriteArrayElem()
			if x.XLog == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_Scalar(([]pkg1_curve25519.Scalar)(x.XLog), e)
			} // end block: if x.XLog slice == nil
			z.EncWriteArrayEnd()
		} else {
			z.EncWriteMapStart(1)
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"x\"")
			} else {
				r.EncodeString(`x`)
			}
			z.EncWriteMapElemValue()
			if x.XLog == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_Scalar(([]pkg1_curve25519.Scalar)(x.XLog), e)
			} // end block: if x.XLog slice == nil
			z.EncWriteMapEnd()
		}
	}
}

func (x *DLWitness) CodecDecodeSelf(d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	yyct2 := r.ContainerType()
	if yyct2 == codecSelferValueTypeNil8453 {
		*(x) = DLWitness{}
	} else if yyct2 == codecSelferValueTypeMap8453 {
		yyl2 := z.DecReadMapStart()
		if yyl2 == 0 {
		} else {
			x.codecDecodeSelfFromMap(yyl2, d)
		}
		z.DecReadMapEnd()
	} else if yyct2 == codecSelferValueTypeArray8453 {
		yyl2 := z.DecReadArrayStart()
		if yyl2 != 0 {
			x.codecDecodeSelfFromArray(yyl2, d)
		}
		z.DecReadArrayEnd()
	} else {
		panic(errCodecSelferOnlyMapOrArrayEncodeToStruct8453)
	}
}

func (x *DLWitness) codecDecodeSelfFromMap(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyhl3 bool = l >= 0
	for yyj3 := 0; ; yyj3++ {
		if yyhl3 {
			if yyj3 >= l {
				break
			}
		} else {
			if z.DecCheckBreak() {
				break
			}
		}
		z.DecReadMapElemKey()
		yys3 := r.DecodeStringAsBytes()
		z.DecReadMapElemValue()
		switch string(yys3) {
		case "x":
			h.decSlicecurve25519_Scalar((*[]pkg1_curve25519.Scalar)(&x.XLog), d)
		default:
			z.DecStructFieldNotFound(-1, string(yys3))
		} // end switch yys3
	} // end for yyj3
}

func (x *DLWitness) codecDecodeSelfFromArray(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyj6 int
	var yyb6 bool
	var yyhl6 bool = l >= 0
	yyj6++
	if yyhl6 {
		yyb6 = yyj6 > l
	} else {
		yyb6 = z.DecCheckBreak()
	}
	if yyb6 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_Scalar((*[]pkg1_curve25519.Scalar)(&x.XLog), d)
	for {
		yyj6++
		if yyhl6 {
			yyb6 = yyj6 > l
		} else {
			yyb6 = z.DecCheckBreak()
		}
		if yyb6 {
			break
		}
		z.DecReadArrayElem()
		z.DecStructFieldNotFound(yyj6-1, "")
	}
}

func (x *DLWitness) IsCodecEmpty() bool {
	return !(len(x.XLog) != 0 || false)
}

func (DLChHashIn) codecSelferViaCodecgen() {}
func (x *DLChHashIn) CodecEncodeSelf(e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if z.EncBasicHandle().CheckCircularRef {
		z.EncEncode(x)
		return
	}
	if x == nil {
		r.EncodeNil()
	} else {
		yy2arr2 := z.EncBasicHandle().StructToArray
		_ = yy2arr2
		const yyr2 bool = false // struct tag has 'toArray'
		if yyr2 || yy2arr2 {
			z.EncWriteArrayStart(2)
			z.EncWriteArrayElem()
			yy5 := &x.Stmt
			if yyxt6 := z.Extension(yy5); yyxt6 != nil {
				z.EncExtension(yy5, yyxt6)
			} else {
				yy5.CodecEncodeSelf(e)
			}
			z.EncWriteArrayElem()
			if x.Com == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.Com), e)
			} // end block: if x.Com slice == nil
			z.EncWriteArrayEnd()
		} else {
			z.EncWriteMapStart(2)
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"s\"")
			} else {
				r.EncodeString(`s`)
			}
			z.EncWriteMapElemValue()
			yy8 := &x.Stmt
			if yyxt9 := z.Extension(yy8); yyxt9 != nil {
				z.EncExtension(yy8, yyxt9)
			} else {
				yy8.CodecEncodeSelf(e)
			}
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"c\"")
			} else {
				r.EncodeString(`c`)
			}
			z.EncWriteMapElemValue()
			if x.Com == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.Com), e)
			} // end block: if x.Com slice == nil
			z.EncWriteMapEnd()
		}
	}
}

func (x *DLChHashIn) CodecDecodeSelf(d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	yyct2 := r.ContainerType()
	if yyct2 == codecSelferValueTypeNil8453 {
		*(x) = DLChHashIn{}
	} else if yyct2 == codecSelferValueTypeMap8453 {
		yyl2 := z.DecReadMapStart()
		if yyl2 == 0 {
		} else {
			x.codecDecodeSelfFromMap(yyl2, d)
		}
		z.DecReadMapEnd()
	} else if yyct2 == codecSelferValueTypeArray8453 {
		yyl2 := z.DecReadArrayStart()
		if yyl2 != 0 {
			x.codecDecodeSelfFromArray(yyl2, d)
		}
		z.DecReadArrayEnd()
	} else {
		panic(errCodecSelferOnlyMapOrArrayEncodeToStruct8453)
	}
}

func (x *DLChHashIn) codecDecodeSelfFromMap(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyhl3 bool = l >= 0
	for yyj3 := 0; ; yyj3++ {
		if yyhl3 {
			if yyj3 >= l {
				break
			}
		} else {
			if z.DecCheckBreak() {
				break
			}
		}
		z.DecReadMapElemKey()
		yys3 := r.DecodeStringAsBytes()
		z.DecReadMapElemValue()
		switch string(yys3) {
		case "s":
			if yyxt5 := z.Extension(x.Stmt); yyxt5 != nil {
				z.DecExtension(&x.Stmt, yyxt5)
			} else {
				x.Stmt.CodecDecodeSelf(d)
			}
		case "c":
			h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.Com), d)
		default:
			z.DecStructFieldNotFound(-1, string(yys3))
		} // end switch yys3
	} // end for yyj3
}

func (x *DLChHashIn) codecDecodeSelfFromArray(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyj8 int
	var yyb8 bool
	var yyhl8 bool = l >= 0
	yyj8++
	if yyhl8 {
		yyb8 = yyj8 > l
	} else {
		yyb8 = z.DecCheckBreak()
	}
	if yyb8 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	if yyxt10 := z.Extension(x.Stmt); yyxt10 != nil {
		z.DecExtension(&x.Stmt, yyxt10)
	} else {
		x.Stmt.CodecDecodeSelf(d)
	}
	yyj8++
	if yyhl8 {
		yyb8 = yyj8 > l
	} else {
		yyb8 = z.DecCheckBreak()
	}
	if yyb8 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.Com), d)
	for {
		yyj8++
		if yyhl8 {
			yyb8 = yyj8 > l
		} else {
			yyb8 = z.DecCheckBreak()
		}
		if yyb8 {
			break
		}
		z.DecReadArrayElem()
		z.DecStructFieldNotFound(yyj8-1, "")
	}
}

func (x *DLChHashIn) IsCodecEmpty() bool {
	return !(!(x.Stmt.IsCodecEmpty()) || len(x.Com) != 0 || false)
}

func (DLProof) codecSelferViaCodecgen() {}
func (x *DLProof) CodecEncodeSelf(e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if z.EncBasicHandle().CheckCircularRef {
		z.EncEncode(x)
		return
	}
	if x == nil {
		r.EncodeNil()
	} else {
		yy2arr2 := z.EncBasicHandle().StructToArray
		_ = yy2arr2
		const yyr2 bool = false // struct tag has 'toArray'
		if yyr2 || yy2arr2 {
			z.EncWriteArrayStart(2)
			z.EncWriteArrayElem()
			if x.Com == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.Com), e)
			} // end block: if x.Com slice == nil
			z.EncWriteArrayElem()
			if x.Resp == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_Scalar(([]pkg1_curve25519.Scalar)(x.Resp), e)
			} // end block: if x.Resp slice == nil
			z.EncWriteArrayEnd()
		} else {
			z.EncWriteMapStart(2)
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"c\"")
			} else {
				r.EncodeString(`c`)
			}
			z.EncWriteMapElemValue()
			if x.Com == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.Com), e)
			} // end block: if x.Com slice == nil
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"r\"")
			} else {
				r.EncodeString(`r`)
			}
			z.EncWriteMapElemValue()
			if x.Resp == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_Scalar(([]pkg1_curve25519.Scalar)(x.Resp), e)
			} // end block: if x.Resp slice == nil
			z.EncWriteMapEnd()
		}
	}
}

func (x *DLProof) CodecDecodeSelf(d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	yyct2 := r.ContainerType()
	if yyct2 == codecSelferValueTypeNil8453 {
		*(x) = DLProof{}
	} else if yyct2 == codecSelferValueTypeMap8453 {
		yyl2 := z.DecReadMapStart()
		if yyl2 == 0 {
		} else {
			x.codecDecodeSelfFromMap(yyl2, d)
		}
		z.DecReadMapEnd()
	} else if yyct2 == codecSelferValueTypeArray8453 {
		yyl2 := z.DecReadArrayStart()
		if yyl2 != 0 {
			x.codecDecodeSelfFromArray(yyl2, d)
		}
		z.DecReadArrayEnd()
	} else {
		panic(errCodecSelferOnlyMapOrArrayEncodeToStruct8453)
	}
}

func (x *DLProof) codecDecodeSelfFromMap(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyhl3 bool = l >= 0
	for yyj3 := 0; ; yyj3++ {
		if yyhl3 {
			if yyj3 >= l {
				break
			}
		} else {
			if z.DecCheckBreak() {
				break
			}
		}
		z.DecReadMapElemKey()
		yys3 := r.DecodeStringAsBytes()
		z.DecReadMapElemValue()
		switch string(yys3) {
		case "c":
			h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.Com), d)
		case "r":
			h.decSlicecurve25519_Scalar((*[]pkg1_curve25519.Scalar)(&x.Resp), d)
		default:
			z.DecStructFieldNotFound(-1, string(yys3))
		} // end switch yys3
	} // end for yyj3
}

func (x *DLProof) codecDecodeSelfFromArray(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyj8 int
	var yyb8 bool
	var yyhl8 bool = l >= 0
	yyj8++
	if yyhl8 {
		yyb8 = yyj8 > l
	} else {
		yyb8 = z.DecCheckBreak()
	}
	if yyb8 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.Com), d)
	yyj8++
	if yyhl8 {
		yyb8 = yyj8 > l
	} else {
		yyb8 = z.DecCheckBreak()
	}
	if yyb8 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_Scalar((*[]pkg1_curve25519.Scalar)(&x.Resp), d)
	for {
		yyj8++
		if yyhl8 {
			yyb8 = yyj8 > l
		} else {
			yyb8 = z.DecCheckBreak()
		}
		if yyb8 {
			break
		}
		z.DecReadArrayElem()
		z.DecStructFieldNotFound(yyj8-1, "")
	}
}

func (x *DLProof) IsCodecEmpty() bool {
	return !(len(x.Com) != 0 || len(x.Resp) != 0 || false)
}

func (DblDLEqStatement) codecSelferViaCodecgen() {}
func (x *DblDLEqStatement) CodecEncodeSelf(e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if z.EncBasicHandle().CheckCircularRef {
		z.EncEncode(x)
		return
	}
	if x == nil {
		r.EncodeNil()
	} else {
		yy2arr2 := z.EncBasicHandle().StructToArray
		_ = yy2arr2
		const yyr2 bool = false // struct tag has 'toArray'
		if yyr2 || yy2arr2 {
			z.EncWriteArrayStart(3)
			z.EncWriteArrayElem()
			if x.G == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.G), e)
			} // end block: if x.G slice == nil
			z.EncWriteArrayElem()
			if x.H == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.H), e)
			} // end block: if x.H slice == nil
			z.EncWriteArrayElem()
			if x.Z == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.Z), e)
			} // end block: if x.Z slice == nil
			z.EncWriteArrayEnd()
		} else {
			z.EncWriteMapStart(3)
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"G\"")
			} else {
				r.EncodeString(`G`)
			}
			z.EncWriteMapElemValue()
			if x.G == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.G), e)
			} // end block: if x.G slice == nil
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"H\"")
			} else {
				r.EncodeString(`H`)
			}
			z.EncWriteMapElemValue()
			if x.H == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.H), e)
			} // end block: if x.H slice == nil
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"Z\"")
			} else {
				r.EncodeString(`Z`)
			}
			z.EncWriteMapElemValue()
			if x.Z == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.Z), e)
			} // end block: if x.Z slice == nil
			z.EncWriteMapEnd()
		}
	}
}

func (x *DblDLEqStatement) CodecDecodeSelf(d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	yyct2 := r.ContainerType()
	if yyct2 == codecSelferValueTypeNil8453 {
		*(x) = DblDLEqStatement{}
	} else if yyct2 == codecSelferValueTypeMap8453 {
		yyl2 := z.DecReadMapStart()
		if yyl2 == 0 {
		} else {
			x.codecDecodeSelfFromMap(yyl2, d)
		}
		z.DecReadMapEnd()
	} else if yyct2 == codecSelferValueTypeArray8453 {
		yyl2 := z.DecReadArrayStart()
		if yyl2 != 0 {
			x.codecDecodeSelfFromArray(yyl2, d)
		}
		z.DecReadArrayEnd()
	} else {
		panic(errCodecSelferOnlyMapOrArrayEncodeToStruct8453)
	}
}

func (x *DblDLEqStatement) codecDecodeSelfFromMap(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyhl3 bool = l >= 0
	for yyj3 := 0; ; yyj3++ {
		if yyhl3 {
			if yyj3 >= l {
				break
			}
		} else {
			if z.DecCheckBreak() {
				break
			}
		}
		z.DecReadMapElemKey()
		yys3 := r.DecodeStringAsBytes()
		z.DecReadMapElemValue()
		switch string(yys3) {
		case "G":
			h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.G), d)
		case "H":
			h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.H), d)
		case "Z":
			h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.Z), d)
		default:
			z.DecStructFieldNotFound(-1, string(yys3))
		} // end switch yys3
	} // end for yyj3
}

func (x *DblDLEqStatement) codecDecodeSelfFromArray(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyj10 int
	var yyb10 bool
	var yyhl10 bool = l >= 0
	yyj10++
	if yyhl10 {
		yyb10 = yyj10 > l
	} else {
		yyb10 = z.DecCheckBreak()
	}
	if yyb10 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.G), d)
	yyj10++
	if yyhl10 {
		yyb10 = yyj10 > l
	} else {
		yyb10 = z.DecCheckBreak()
	}
	if yyb10 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.H), d)
	yyj10++
	if yyhl10 {
		yyb10 = yyj10 > l
	} else {
		yyb10 = z.DecCheckBreak()
	}
	if yyb10 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.Z), d)
	for {
		yyj10++
		if yyhl10 {
			yyb10 = yyj10 > l
		} else {
			yyb10 = z.DecCheckBreak()
		}
		if yyb10 {
			break
		}
		z.DecReadArrayElem()
		z.DecStructFieldNotFound(yyj10-1, "")
	}
}

func (x *DblDLEqStatement) IsCodecEmpty() bool {
	return !(len(x.G) != 0 || len(x.H) != 0 || len(x.Z) != 0 || false)
}

func (DblDLEqWitness) codecSelferViaCodecgen() {}
func (x *DblDLEqWitness) CodecEncodeSelf(e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if z.EncBasicHandle().CheckCircularRef {
		z.EncEncode(x)
		return
	}
	if x == nil {
		r.EncodeNil()
	} else {
		yy2arr2 := z.EncBasicHandle().StructToArray
		_ = yy2arr2
		const yyr2 bool = false // struct tag has 'toArray'
		if yyr2 || yy2arr2 {
			z.EncWriteArrayStart(2)
			z.EncWriteArrayElem()
			if x.X == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_Scalar(([]pkg1_curve25519.Scalar)(x.X), e)
			} // end block: if x.X slice == nil
			z.EncWriteArrayElem()
			if x.Y == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_Scalar(([]pkg1_curve25519.Scalar)(x.Y), e)
			} // end block: if x.Y slice == nil
			z.EncWriteArrayEnd()
		} else {
			z.EncWriteMapStart(2)
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"x\"")
			} else {
				r.EncodeString(`x`)
			}
			z.EncWriteMapElemValue()
			if x.X == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_Scalar(([]pkg1_curve25519.Scalar)(x.X), e)
			} // end block: if x.X slice == nil
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"y\"")
			} else {
				r.EncodeString(`y`)
			}
			z.EncWriteMapElemValue()
			if x.Y == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_Scalar(([]pkg1_curve25519.Scalar)(x.Y), e)
			} // end block: if x.Y slice == nil
			z.EncWriteMapEnd()
		}
	}
}

func (x *DblDLEqWitness) CodecDecodeSelf(d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	yyct2 := r.ContainerType()
	if yyct2 == codecSelferValueTypeNil8453 {
		*(x) = DblDLEqWitness{}
	} else if yyct2 == codecSelferValueTypeMap8453 {
		yyl2 := z.DecReadMapStart()
		if yyl2 == 0 {
		} else {
			x.codecDecodeSelfFromMap(yyl2, d)
		}
		z.DecReadMapEnd()
	} else if yyct2 == codecSelferValueTypeArray8453 {
		yyl2 := z.DecReadArrayStart()
		if yyl2 != 0 {
			x.codecDecodeSelfFromArray(yyl2, d)
		}
		z.DecReadArrayEnd()
	} else {
		panic(errCodecSelferOnlyMapOrArrayEncodeToStruct8453)
	}
}

func (x *DblDLEqWitness) codecDecodeSelfFromMap(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyhl3 bool = l >= 0
	for yyj3 := 0; ; yyj3++ {
		if yyhl3 {
			if yyj3 >= l {
				break
			}
		} else {
			if z.DecCheckBreak() {
				break
			}
		}
		z.DecReadMapElemKey()
		yys3 := r.DecodeStringAsBytes()
		z.DecReadMapElemValue()
		switch string(yys3) {
		case "x":
			h.decSlicecurve25519_Scalar((*[]pkg1_curve25519.Scalar)(&x.X), d)
		case "y":
			h.decSlicecurve25519_Scalar((*[]pkg1_curve25519.Scalar)(&x.Y), d)
		default:
			z.DecStructFieldNotFound(-1, string(yys3))
		} // end switch yys3
	} // end for yyj3
}

func (x *DblDLEqWitness) codecDecodeSelfFromArray(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyj8 int
	var yyb8 bool
	var yyhl8 bool = l >= 0
	yyj8++
	if yyhl8 {
		yyb8 = yyj8 > l
	} else {
		yyb8 = z.DecCheckBreak()
	}
	if yyb8 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_Scalar((*[]pkg1_curve25519.Scalar)(&x.X), d)
	yyj8++
	if yyhl8 {
		yyb8 = yyj8 > l
	} else {
		yyb8 = z.DecCheckBreak()
	}
	if yyb8 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_Scalar((*[]pkg1_curve25519.Scalar)(&x.Y), d)
	for {
		yyj8++
		if yyhl8 {
			yyb8 = yyj8 > l
		} else {
			yyb8 = z.DecCheckBreak()
		}
		if yyb8 {
			break
		}
		z.DecReadArrayElem()
		z.DecStructFieldNotFound(yyj8-1, "")
	}
}

func (x *DblDLEqWitness) IsCodecEmpty() bool {
	return !(len(x.X) != 0 || len(x.Y) != 0 || false)
}

func (DblDLEqHashIn) codecSelferViaCodecgen() {}
func (x *DblDLEqHashIn) CodecEncodeSelf(e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if z.EncBasicHandle().CheckCircularRef {
		z.EncEncode(x)
		return
	}
	if x == nil {
		r.EncodeNil()
	} else {
		yy2arr2 := z.EncBasicHandle().StructToArray
		_ = yy2arr2
		const yyr2 bool = false // struct tag has 'toArray'
		if yyr2 || yy2arr2 {
			z.EncWriteArrayStart(3)
			z.EncWriteArrayElem()
			yy6 := &x.Stmt
			if yyxt7 := z.Extension(yy6); yyxt7 != nil {
				z.EncExtension(yy6, yyxt7)
			} else {
				yy6.CodecEncodeSelf(e)
			}
			z.EncWriteArrayElem()
			if x.Com == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.Com), e)
			} // end block: if x.Com slice == nil
			z.EncWriteArrayElem()
			if x.ComPrime == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.ComPrime), e)
			} // end block: if x.ComPrime slice == nil
			z.EncWriteArrayEnd()
		} else {
			z.EncWriteMapStart(3)
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"s\"")
			} else {
				r.EncodeString(`s`)
			}
			z.EncWriteMapElemValue()
			yy10 := &x.Stmt
			if yyxt11 := z.Extension(yy10); yyxt11 != nil {
				z.EncExtension(yy10, yyxt11)
			} else {
				yy10.CodecEncodeSelf(e)
			}
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"g\"")
			} else {
				r.EncodeString(`g`)
			}
			z.EncWriteMapElemValue()
			if x.Com == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.Com), e)
			} // end block: if x.Com slice == nil
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"h\"")
			} else {
				r.EncodeString(`h`)
			}
			z.EncWriteMapElemValue()
			if x.ComPrime == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.ComPrime), e)
			} // end block: if x.ComPrime slice == nil
			z.EncWriteMapEnd()
		}
	}
}

func (x *DblDLEqHashIn) CodecDecodeSelf(d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	yyct2 := r.ContainerType()
	if yyct2 == codecSelferValueTypeNil8453 {
		*(x) = DblDLEqHashIn{}
	} else if yyct2 == codecSelferValueTypeMap8453 {
		yyl2 := z.DecReadMapStart()
		if yyl2 == 0 {
		} else {
			x.codecDecodeSelfFromMap(yyl2, d)
		}
		z.DecReadMapEnd()
	} else if yyct2 == codecSelferValueTypeArray8453 {
		yyl2 := z.DecReadArrayStart()
		if yyl2 != 0 {
			x.codecDecodeSelfFromArray(yyl2, d)
		}
		z.DecReadArrayEnd()
	} else {
		panic(errCodecSelferOnlyMapOrArrayEncodeToStruct8453)
	}
}

func (x *DblDLEqHashIn) codecDecodeSelfFromMap(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyhl3 bool = l >= 0
	for yyj3 := 0; ; yyj3++ {
		if yyhl3 {
			if yyj3 >= l {
				break
			}
		} else {
			if z.DecCheckBreak() {
				break
			}
		}
		z.DecReadMapElemKey()
		yys3 := r.DecodeStringAsBytes()
		z.DecReadMapElemValue()
		switch string(yys3) {
		case "s":
			if yyxt5 := z.Extension(x.Stmt); yyxt5 != nil {
				z.DecExtension(&x.Stmt, yyxt5)
			} else {
				x.Stmt.CodecDecodeSelf(d)
			}
		case "g":
			h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.Com), d)
		case "h":
			h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.ComPrime), d)
		default:
			z.DecStructFieldNotFound(-1, string(yys3))
		} // end switch yys3
	} // end for yyj3
}

func (x *DblDLEqHashIn) codecDecodeSelfFromArray(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyj10 int
	var yyb10 bool
	var yyhl10 bool = l >= 0
	yyj10++
	if yyhl10 {
		yyb10 = yyj10 > l
	} else {
		yyb10 = z.DecCheckBreak()
	}
	if yyb10 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	if yyxt12 := z.Extension(x.Stmt); yyxt12 != nil {
		z.DecExtension(&x.Stmt, yyxt12)
	} else {
		x.Stmt.CodecDecodeSelf(d)
	}
	yyj10++
	if yyhl10 {
		yyb10 = yyj10 > l
	} else {
		yyb10 = z.DecCheckBreak()
	}
	if yyb10 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.Com), d)
	yyj10++
	if yyhl10 {
		yyb10 = yyj10 > l
	} else {
		yyb10 = z.DecCheckBreak()
	}
	if yyb10 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.ComPrime), d)
	for {
		yyj10++
		if yyhl10 {
			yyb10 = yyj10 > l
		} else {
			yyb10 = z.DecCheckBreak()
		}
		if yyb10 {
			break
		}
		z.DecReadArrayElem()
		z.DecStructFieldNotFound(yyj10-1, "")
	}
}

func (x *DblDLEqHashIn) IsCodecEmpty() bool {
	return !(!(x.Stmt.IsCodecEmpty()) || len(x.Com) != 0 || len(x.ComPrime) != 0 || false)
}

func (DblDLEqProof) codecSelferViaCodecgen() {}
func (x *DblDLEqProof) CodecEncodeSelf(e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if z.EncBasicHandle().CheckCircularRef {
		z.EncEncode(x)
		return
	}
	if x == nil {
		r.EncodeNil()
	} else {
		yy2arr2 := z.EncBasicHandle().StructToArray
		_ = yy2arr2
		const yyr2 bool = false // struct tag has 'toArray'
		if yyr2 || yy2arr2 {
			z.EncWriteArrayStart(4)
			z.EncWriteArrayElem()
			if x.Com == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.Com), e)
			} // end block: if x.Com slice == nil
			z.EncWriteArrayElem()
			if x.ComPrime == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.ComPrime), e)
			} // end block: if x.ComPrime slice == nil
			z.EncWriteArrayElem()
			if x.RespG == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_Scalar(([]pkg1_curve25519.Scalar)(x.RespG), e)
			} // end block: if x.RespG slice == nil
			z.EncWriteArrayElem()
			if x.RespH == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_Scalar(([]pkg1_curve25519.Scalar)(x.RespH), e)
			} // end block: if x.RespH slice == nil
			z.EncWriteArrayEnd()
		} else {
			z.EncWriteMapStart(4)
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"g\"")
			} else {
				r.EncodeString(`g`)
			}
			z.EncWriteMapElemValue()
			if x.Com == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.Com), e)
			} // end block: if x.Com slice == nil
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"h\"")
			} else {
				r.EncodeString(`h`)
			}
			z.EncWriteMapElemValue()
			if x.ComPrime == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.ComPrime), e)
			} // end block: if x.ComPrime slice == nil
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"G\"")
			} else {
				r.EncodeString(`G`)
			}
			z.EncWriteMapElemValue()
			if x.RespG == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_Scalar(([]pkg1_curve25519.Scalar)(x.RespG), e)
			} // end block: if x.RespG slice == nil
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"H\"")
			} else {
				r.EncodeString(`H`)
			}
			z.EncWriteMapElemValue()
			if x.RespH == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_Scalar(([]pkg1_curve25519.Scalar)(x.RespH), e)
			} // end block: if x.RespH slice == nil
			z.EncWriteMapEnd()
		}
	}
}

func (x *DblDLEqProof) CodecDecodeSelf(d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	yyct2 := r.ContainerType()
	if yyct2 == codecSelferValueTypeNil8453 {
		*(x) = DblDLEqProof{}
	} else if yyct2 == codecSelferValueTypeMap8453 {
		yyl2 := z.DecReadMapStart()
		if yyl2 == 0 {
		} else {
			x.codecDecodeSelfFromMap(yyl2, d)
		}
		z.DecReadMapEnd()
	} else if yyct2 == codecSelferValueTypeArray8453 {
		yyl2 := z.DecReadArrayStart()
		if yyl2 != 0 {
			x.codecDecodeSelfFromArray(yyl2, d)
		}
		z.DecReadArrayEnd()
	} else {
		panic(errCodecSelferOnlyMapOrArrayEncodeToStruct8453)
	}
}

func (x *DblDLEqProof) codecDecodeSelfFromMap(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyhl3 bool = l >= 0
	for yyj3 := 0; ; yyj3++ {
		if yyhl3 {
			if yyj3 >= l {
				break
			}
		} else {
			if z.DecCheckBreak() {
				break
			}
		}
		z.DecReadMapElemKey()
		yys3 := r.DecodeStringAsBytes()
		z.DecReadMapElemValue()
		switch string(yys3) {
		case "g":
			h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.Com), d)
		case "h":
			h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.ComPrime), d)
		case "G":
			h.decSlicecurve25519_Scalar((*[]pkg1_curve25519.Scalar)(&x.RespG), d)
		case "H":
			h.decSlicecurve25519_Scalar((*[]pkg1_curve25519.Scalar)(&x.RespH), d)
		default:
			z.DecStructFieldNotFound(-1, string(yys3))
		} // end switch yys3
	} // end for yyj3
}

func (x *DblDLEqProof) codecDecodeSelfFromArray(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyj12 int
	var yyb12 bool
	var yyhl12 bool = l >= 0
	yyj12++
	if yyhl12 {
		yyb12 = yyj12 > l
	} else {
		yyb12 = z.DecCheckBreak()
	}
	if yyb12 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.Com), d)
	yyj12++
	if yyhl12 {
		yyb12 = yyj12 > l
	} else {
		yyb12 = z.DecCheckBreak()
	}
	if yyb12 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.ComPrime), d)
	yyj12++
	if yyhl12 {
		yyb12 = yyj12 > l
	} else {
		yyb12 = z.DecCheckBreak()
	}
	if yyb12 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_Scalar((*[]pkg1_curve25519.Scalar)(&x.RespG), d)
	yyj12++
	if yyhl12 {
		yyb12 = yyj12 > l
	} else {
		yyb12 = z.DecCheckBreak()
	}
	if yyb12 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_Scalar((*[]pkg1_curve25519.Scalar)(&x.RespH), d)
	for {
		yyj12++
		if yyhl12 {
			yyb12 = yyj12 > l
		} else {
			yyb12 = z.DecCheckBreak()
		}
		if yyb12 {
			break
		}
		z.DecReadArrayElem()
		z.DecStructFieldNotFound(yyj12-1, "")
	}
}

func (x *DblDLEqProof) IsCodecEmpty() bool {
	return !(len(x.Com) != 0 || len(x.ComPrime) != 0 || len(x.RespG) != 0 || len(x.RespH) != 0 || false)
}

func (DealingMessage) codecSelferViaCodecgen() {}
func (x *DealingMessage) CodecEncodeSelf(e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if z.EncBasicHandle().CheckCircularRef {
		z.EncEncode(x)
		return
	}
	if x == nil {
		r.EncodeNil()
	} else {
		yy2arr2 := z.EncBasicHandle().StructToArray
		_ = yy2arr2
		const yyr2 bool = false // struct tag has 'toArray'
		var yyq2 = [8]bool{     // should field at this index be written?
			len(x.ComC) != 0,                 // C
			len(x.ComZ) != 0,                 // Z
			len(x.ComZPrime) != 0,            // z
			!(x.DblDLEqProof.IsCodecEmpty()), // p
			len(x.EncVerM) != 0,              // V
			len(x.EncResM) != 0,              // R
			len(x.EncEpsK) != 0,              // e
			len(x.HashEps) != 0,              // h
		}
		_ = yyq2
		if yyr2 || yy2arr2 {
			z.EncWriteArrayStart(8)
			z.EncWriteArrayElem()
			if yyq2[0] {
				if x.ComC == nil {
					r.EncodeNil()
				} else {
					h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.ComC), e)
				} // end block: if x.ComC slice == nil
			} else {
				r.EncodeNil()
			}
			z.EncWriteArrayElem()
			if yyq2[1] {
				if x.ComZ == nil {
					r.EncodeNil()
				} else {
					h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.ComZ), e)
				} // end block: if x.ComZ slice == nil
			} else {
				r.EncodeNil()
			}
			z.EncWriteArrayElem()
			if yyq2[2] {
				if x.ComZPrime == nil {
					r.EncodeNil()
				} else {
					h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.ComZPrime), e)
				} // end block: if x.ComZPrime slice == nil
			} else {
				r.EncodeNil()
			}
			z.EncWriteArrayElem()
			if yyq2[3] {
				yy14 := &x.DblDLEqProof
				if yyxt15 := z.Extension(yy14); yyxt15 != nil {
					z.EncExtension(yy14, yyxt15)
				} else {
					yy14.CodecEncodeSelf(e)
				}
			} else {
				r.EncodeNil()
			}
			z.EncWriteArrayElem()
			if yyq2[4] {
				if x.EncVerM == nil {
					r.EncodeNil()
				} else {
					h.encSlicecurve25519_Ciphertext(([]pkg1_curve25519.Ciphertext)(x.EncVerM), e)
				} // end block: if x.EncVerM slice == nil
			} else {
				r.EncodeNil()
			}
			z.EncWriteArrayElem()
			if yyq2[5] {
				if x.EncResM == nil {
					r.EncodeNil()
				} else {
					h.encSlicecurve25519_SymmetricCiphertext(([]pkg1_curve25519.SymmetricCiphertext)(x.EncResM), e)
				} // end block: if x.EncResM slice == nil
			} else {
				r.EncodeNil()
			}
			z.EncWriteArrayElem()
			if yyq2[6] {
				if x.EncEpsK == nil {
					r.EncodeNil()
				} else {
					h.encSlicecurve25519_Ciphertext(([]pkg1_curve25519.Ciphertext)(x.EncEpsK), e)
				} // end block: if x.EncEpsK slice == nil
			} else {
				r.EncodeNil()
			}
			z.EncWriteArrayElem()
			if yyq2[7] {
				if x.HashEps == nil {
					r.EncodeNil()
				} else {
					h.encSliceSliceArray32uint8(([][][32]uint8)(x.HashEps), e)
				} // end block: if x.HashEps slice == nil
			} else {
				r.EncodeNil()
			}
			z.EncWriteArrayEnd()
		} else {
			var yynn2 int
			for _, b := range yyq2 {
				if b {
					yynn2++
				}
			}
			z.EncWriteMapStart(yynn2)
			yynn2 = 0
			if yyq2[0] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"C\"")
				} else {
					r.EncodeString(`C`)
				}
				z.EncWriteMapElemValue()
				if x.ComC == nil {
					r.EncodeNil()
				} else {
					h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.ComC), e)
				} // end block: if x.ComC slice == nil
			}
			if yyq2[1] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"Z\"")
				} else {
					r.EncodeString(`Z`)
				}
				z.EncWriteMapElemValue()
				if x.ComZ == nil {
					r.EncodeNil()
				} else {
					h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.ComZ), e)
				} // end block: if x.ComZ slice == nil
			}
			if yyq2[2] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"z\"")
				} else {
					r.EncodeString(`z`)
				}
				z.EncWriteMapElemValue()
				if x.ComZPrime == nil {
					r.EncodeNil()
				} else {
					h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.ComZPrime), e)
				} // end block: if x.ComZPrime slice == nil
			}
			if yyq2[3] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"p\"")
				} else {
					r.EncodeString(`p`)
				}
				z.EncWriteMapElemValue()
				yy23 := &x.DblDLEqProof
				if yyxt24 := z.Extension(yy23); yyxt24 != nil {
					z.EncExtension(yy23, yyxt24)
				} else {
					yy23.CodecEncodeSelf(e)
				}
			}
			if yyq2[4] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"V\"")
				} else {
					r.EncodeString(`V`)
				}
				z.EncWriteMapElemValue()
				if x.EncVerM == nil {
					r.EncodeNil()
				} else {
					h.encSlicecurve25519_Ciphertext(([]pkg1_curve25519.Ciphertext)(x.EncVerM), e)
				} // end block: if x.EncVerM slice == nil
			}
			if yyq2[5] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"R\"")
				} else {
					r.EncodeString(`R`)
				}
				z.EncWriteMapElemValue()
				if x.EncResM == nil {
					r.EncodeNil()
				} else {
					h.encSlicecurve25519_SymmetricCiphertext(([]pkg1_curve25519.SymmetricCiphertext)(x.EncResM), e)
				} // end block: if x.EncResM slice == nil
			}
			if yyq2[6] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"e\"")
				} else {
					r.EncodeString(`e`)
				}
				z.EncWriteMapElemValue()
				if x.EncEpsK == nil {
					r.EncodeNil()
				} else {
					h.encSlicecurve25519_Ciphertext(([]pkg1_curve25519.Ciphertext)(x.EncEpsK), e)
				} // end block: if x.EncEpsK slice == nil
			}
			if yyq2[7] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"h\"")
				} else {
					r.EncodeString(`h`)
				}
				z.EncWriteMapElemValue()
				if x.HashEps == nil {
					r.EncodeNil()
				} else {
					h.encSliceSliceArray32uint8(([][][32]uint8)(x.HashEps), e)
				} // end block: if x.HashEps slice == nil
			}
			z.EncWriteMapEnd()
		}
	}
}

func (x *DealingMessage) CodecDecodeSelf(d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	yyct2 := r.ContainerType()
	if yyct2 == codecSelferValueTypeNil8453 {
		*(x) = DealingMessage{}
	} else if yyct2 == codecSelferValueTypeMap8453 {
		yyl2 := z.DecReadMapStart()
		if yyl2 == 0 {
		} else {
			x.codecDecodeSelfFromMap(yyl2, d)
		}
		z.DecReadMapEnd()
	} else if yyct2 == codecSelferValueTypeArray8453 {
		yyl2 := z.DecReadArrayStart()
		if yyl2 != 0 {
			x.codecDecodeSelfFromArray(yyl2, d)
		}
		z.DecReadArrayEnd()
	} else {
		panic(errCodecSelferOnlyMapOrArrayEncodeToStruct8453)
	}
}

func (x *DealingMessage) codecDecodeSelfFromMap(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyhl3 bool = l >= 0
	for yyj3 := 0; ; yyj3++ {
		if yyhl3 {
			if yyj3 >= l {
				break
			}
		} else {
			if z.DecCheckBreak() {
				break
			}
		}
		z.DecReadMapElemKey()
		yys3 := r.DecodeStringAsBytes()
		z.DecReadMapElemValue()
		switch string(yys3) {
		case "C":
			h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.ComC), d)
		case "Z":
			h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.ComZ), d)
		case "z":
			h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.ComZPrime), d)
		case "p":
			if yyxt11 := z.Extension(x.DblDLEqProof); yyxt11 != nil {
				z.DecExtension(&x.DblDLEqProof, yyxt11)
			} else {
				x.DblDLEqProof.CodecDecodeSelf(d)
			}
		case "V":
			h.decSlicecurve25519_Ciphertext((*[]pkg1_curve25519.Ciphertext)(&x.EncVerM), d)
		case "R":
			h.decSlicecurve25519_SymmetricCiphertext((*[]pkg1_curve25519.SymmetricCiphertext)(&x.EncResM), d)
		case "e":
			h.decSlicecurve25519_Ciphertext((*[]pkg1_curve25519.Ciphertext)(&x.EncEpsK), d)
		case "h":
			h.decSliceSliceArray32uint8((*[][][32]uint8)(&x.HashEps), d)
		default:
			z.DecStructFieldNotFound(-1, string(yys3))
		} // end switch yys3
	} // end for yyj3
}

func (x *DealingMessage) codecDecodeSelfFromArray(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyj20 int
	var yyb20 bool
	var yyhl20 bool = l >= 0
	yyj20++
	if yyhl20 {
		yyb20 = yyj20 > l
	} else {
		yyb20 = z.DecCheckBreak()
	}
	if yyb20 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.ComC), d)
	yyj20++
	if yyhl20 {
		yyb20 = yyj20 > l
	} else {
		yyb20 = z.DecCheckBreak()
	}
	if yyb20 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.ComZ), d)
	yyj20++
	if yyhl20 {
		yyb20 = yyj20 > l
	} else {
		yyb20 = z.DecCheckBreak()
	}
	if yyb20 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.ComZPrime), d)
	yyj20++
	if yyhl20 {
		yyb20 = yyj20 > l
	} else {
		yyb20 = z.DecCheckBreak()
	}
	if yyb20 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	if yyxt28 := z.Extension(x.DblDLEqProof); yyxt28 != nil {
		z.DecExtension(&x.DblDLEqProof, yyxt28)
	} else {
		x.DblDLEqProof.CodecDecodeSelf(d)
	}
	yyj20++
	if yyhl20 {
		yyb20 = yyj20 > l
	} else {
		yyb20 = z.DecCheckBreak()
	}
	if yyb20 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_Ciphertext((*[]pkg1_curve25519.Ciphertext)(&x.EncVerM), d)
	yyj20++
	if yyhl20 {
		yyb20 = yyj20 > l
	} else {
		yyb20 = z.DecCheckBreak()
	}
	if yyb20 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_SymmetricCiphertext((*[]pkg1_curve25519.SymmetricCiphertext)(&x.EncResM), d)
	yyj20++
	if yyhl20 {
		yyb20 = yyj20 > l
	} else {
		yyb20 = z.DecCheckBreak()
	}
	if yyb20 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_Ciphertext((*[]pkg1_curve25519.Ciphertext)(&x.EncEpsK), d)
	yyj20++
	if yyhl20 {
		yyb20 = yyj20 > l
	} else {
		yyb20 = z.DecCheckBreak()
	}
	if yyb20 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSliceSliceArray32uint8((*[][][32]uint8)(&x.HashEps), d)
	for {
		yyj20++
		if yyhl20 {
			yyb20 = yyj20 > l
		} else {
			yyb20 = z.DecCheckBreak()
		}
		if yyb20 {
			break
		}
		z.DecReadArrayElem()
		z.DecStructFieldNotFound(yyj20-1, "")
	}
}

func (x *DealingMessage) IsCodecEmpty() bool {
	return !(len(x.ComC) != 0 || len(x.ComZ) != 0 || len(x.ComZPrime) != 0 || !(x.DblDLEqProof.IsCodecEmpty()) || len(x.EncVerM) != 0 || len(x.EncResM) != 0 || len(x.EncEpsK) != 0 || len(x.HashEps) != 0 || false)
}

func (VerificationMJ) codecSelferViaCodecgen() {}
func (x *VerificationMJ) CodecEncodeSelf(e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if z.EncBasicHandle().CheckCircularRef {
		z.EncEncode(x)
		return
	}
	if x == nil {
		r.EncodeNil()
	} else {
		yy2arr2 := z.EncBasicHandle().StructToArray
		_ = yy2arr2
		const yyr2 bool = false // struct tag has 'toArray'
		if yyr2 || yy2arr2 {
			z.EncWriteArrayStart(1)
			z.EncWriteArrayElem()
			if x.SR == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_Scalar(([]pkg1_curve25519.Scalar)(x.SR), e)
			} // end block: if x.SR slice == nil
			z.EncWriteArrayEnd()
		} else {
			z.EncWriteMapStart(1)
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"SR\"")
			} else {
				r.EncodeString(`SR`)
			}
			z.EncWriteMapElemValue()
			if x.SR == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_Scalar(([]pkg1_curve25519.Scalar)(x.SR), e)
			} // end block: if x.SR slice == nil
			z.EncWriteMapEnd()
		}
	}
}

func (x *VerificationMJ) CodecDecodeSelf(d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	yyct2 := r.ContainerType()
	if yyct2 == codecSelferValueTypeNil8453 {
		*(x) = VerificationMJ{}
	} else if yyct2 == codecSelferValueTypeMap8453 {
		yyl2 := z.DecReadMapStart()
		if yyl2 == 0 {
		} else {
			x.codecDecodeSelfFromMap(yyl2, d)
		}
		z.DecReadMapEnd()
	} else if yyct2 == codecSelferValueTypeArray8453 {
		yyl2 := z.DecReadArrayStart()
		if yyl2 != 0 {
			x.codecDecodeSelfFromArray(yyl2, d)
		}
		z.DecReadArrayEnd()
	} else {
		panic(errCodecSelferOnlyMapOrArrayEncodeToStruct8453)
	}
}

func (x *VerificationMJ) codecDecodeSelfFromMap(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyhl3 bool = l >= 0
	for yyj3 := 0; ; yyj3++ {
		if yyhl3 {
			if yyj3 >= l {
				break
			}
		} else {
			if z.DecCheckBreak() {
				break
			}
		}
		z.DecReadMapElemKey()
		yys3 := r.DecodeStringAsBytes()
		z.DecReadMapElemValue()
		switch string(yys3) {
		case "SR":
			h.decSlicecurve25519_Scalar((*[]pkg1_curve25519.Scalar)(&x.SR), d)
		default:
			z.DecStructFieldNotFound(-1, string(yys3))
		} // end switch yys3
	} // end for yyj3
}

func (x *VerificationMJ) codecDecodeSelfFromArray(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyj6 int
	var yyb6 bool
	var yyhl6 bool = l >= 0
	yyj6++
	if yyhl6 {
		yyb6 = yyj6 > l
	} else {
		yyb6 = z.DecCheckBreak()
	}
	if yyb6 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_Scalar((*[]pkg1_curve25519.Scalar)(&x.SR), d)
	for {
		yyj6++
		if yyhl6 {
			yyb6 = yyj6 > l
		} else {
			yyb6 = z.DecCheckBreak()
		}
		if yyb6 {
			break
		}
		z.DecReadArrayElem()
		z.DecStructFieldNotFound(yyj6-1, "")
	}
}

func (x *VerificationMJ) IsCodecEmpty() bool {
	return !(len(x.SR) != 0 || false)
}

func (EpsK) codecSelferViaCodecgen() {}
func (x *EpsK) CodecEncodeSelf(e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if z.EncBasicHandle().CheckCircularRef {
		z.EncEncode(x)
		return
	}
	if x == nil {
		r.EncodeNil()
	} else {
		yy2arr2 := z.EncBasicHandle().StructToArray
		_ = yy2arr2
		const yyr2 bool = false // struct tag has 'toArray'
		if yyr2 || yy2arr2 {
			z.EncWriteArrayStart(1)
			z.EncWriteArrayElem()
			if x.Eps == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_Scalar(([]pkg1_curve25519.Scalar)(x.Eps), e)
			} // end block: if x.Eps slice == nil
			z.EncWriteArrayEnd()
		} else {
			z.EncWriteMapStart(1)
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"Eps\"")
			} else {
				r.EncodeString(`Eps`)
			}
			z.EncWriteMapElemValue()
			if x.Eps == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_Scalar(([]pkg1_curve25519.Scalar)(x.Eps), e)
			} // end block: if x.Eps slice == nil
			z.EncWriteMapEnd()
		}
	}
}

func (x *EpsK) CodecDecodeSelf(d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	yyct2 := r.ContainerType()
	if yyct2 == codecSelferValueTypeNil8453 {
		*(x) = EpsK{}
	} else if yyct2 == codecSelferValueTypeMap8453 {
		yyl2 := z.DecReadMapStart()
		if yyl2 == 0 {
		} else {
			x.codecDecodeSelfFromMap(yyl2, d)
		}
		z.DecReadMapEnd()
	} else if yyct2 == codecSelferValueTypeArray8453 {
		yyl2 := z.DecReadArrayStart()
		if yyl2 != 0 {
			x.codecDecodeSelfFromArray(yyl2, d)
		}
		z.DecReadArrayEnd()
	} else {
		panic(errCodecSelferOnlyMapOrArrayEncodeToStruct8453)
	}
}

func (x *EpsK) codecDecodeSelfFromMap(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyhl3 bool = l >= 0
	for yyj3 := 0; ; yyj3++ {
		if yyhl3 {
			if yyj3 >= l {
				break
			}
		} else {
			if z.DecCheckBreak() {
				break
			}
		}
		z.DecReadMapElemKey()
		yys3 := r.DecodeStringAsBytes()
		z.DecReadMapElemValue()
		switch string(yys3) {
		case "Eps":
			h.decSlicecurve25519_Scalar((*[]pkg1_curve25519.Scalar)(&x.Eps), d)
		default:
			z.DecStructFieldNotFound(-1, string(yys3))
		} // end switch yys3
	} // end for yyj3
}

func (x *EpsK) codecDecodeSelfFromArray(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyj6 int
	var yyb6 bool
	var yyhl6 bool = l >= 0
	yyj6++
	if yyhl6 {
		yyb6 = yyj6 > l
	} else {
		yyb6 = z.DecCheckBreak()
	}
	if yyb6 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_Scalar((*[]pkg1_curve25519.Scalar)(&x.Eps), d)
	for {
		yyj6++
		if yyhl6 {
			yyb6 = yyj6 > l
		} else {
			yyb6 = z.DecCheckBreak()
		}
		if yyb6 {
			break
		}
		z.DecReadArrayElem()
		z.DecStructFieldNotFound(yyj6-1, "")
	}
}

func (x *EpsK) IsCodecEmpty() bool {
	return !(len(x.Eps) != 0 || false)
}

func (VerSentShares) codecSelferViaCodecgen() {}
func (x *VerSentShares) CodecEncodeSelf(e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if z.EncBasicHandle().CheckCircularRef {
		z.EncEncode(x)
		return
	}
	if x == nil {
		r.EncodeNil()
	} else {
		yy2arr2 := z.EncBasicHandle().StructToArray
		_ = yy2arr2
		const yyr2 bool = false // struct tag has 'toArray'
		if yyr2 || yy2arr2 {
			z.EncWriteArrayStart(2)
			z.EncWriteArrayElem()
			if x.S == nil {
				r.EncodeNil()
			} else {
				h.encSlicePtrtocurve25519_Scalar(([]*pkg1_curve25519.Scalar)(x.S), e)
			} // end block: if x.S slice == nil
			z.EncWriteArrayElem()
			if x.R == nil {
				r.EncodeNil()
			} else {
				h.encSlicePtrtocurve25519_Scalar(([]*pkg1_curve25519.Scalar)(x.R), e)
			} // end block: if x.R slice == nil
			z.EncWriteArrayEnd()
		} else {
			z.EncWriteMapStart(2)
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"S\"")
			} else {
				r.EncodeString(`S`)
			}
			z.EncWriteMapElemValue()
			if x.S == nil {
				r.EncodeNil()
			} else {
				h.encSlicePtrtocurve25519_Scalar(([]*pkg1_curve25519.Scalar)(x.S), e)
			} // end block: if x.S slice == nil
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"R\"")
			} else {
				r.EncodeString(`R`)
			}
			z.EncWriteMapElemValue()
			if x.R == nil {
				r.EncodeNil()
			} else {
				h.encSlicePtrtocurve25519_Scalar(([]*pkg1_curve25519.Scalar)(x.R), e)
			} // end block: if x.R slice == nil
			z.EncWriteMapEnd()
		}
	}
}

func (x *VerSentShares) CodecDecodeSelf(d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	yyct2 := r.ContainerType()
	if yyct2 == codecSelferValueTypeNil8453 {
		*(x) = VerSentShares{}
	} else if yyct2 == codecSelferValueTypeMap8453 {
		yyl2 := z.DecReadMapStart()
		if yyl2 == 0 {
		} else {
			x.codecDecodeSelfFromMap(yyl2, d)
		}
		z.DecReadMapEnd()
	} else if yyct2 == codecSelferValueTypeArray8453 {
		yyl2 := z.DecReadArrayStart()
		if yyl2 != 0 {
			x.codecDecodeSelfFromArray(yyl2, d)
		}
		z.DecReadArrayEnd()
	} else {
		panic(errCodecSelferOnlyMapOrArrayEncodeToStruct8453)
	}
}

func (x *VerSentShares) codecDecodeSelfFromMap(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyhl3 bool = l >= 0
	for yyj3 := 0; ; yyj3++ {
		if yyhl3 {
			if yyj3 >= l {
				break
			}
		} else {
			if z.DecCheckBreak() {
				break
			}
		}
		z.DecReadMapElemKey()
		yys3 := r.DecodeStringAsBytes()
		z.DecReadMapElemValue()
		switch string(yys3) {
		case "S":
			h.decSlicePtrtocurve25519_Scalar((*[]*pkg1_curve25519.Scalar)(&x.S), d)
		case "R":
			h.decSlicePtrtocurve25519_Scalar((*[]*pkg1_curve25519.Scalar)(&x.R), d)
		default:
			z.DecStructFieldNotFound(-1, string(yys3))
		} // end switch yys3
	} // end for yyj3
}

func (x *VerSentShares) codecDecodeSelfFromArray(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyj8 int
	var yyb8 bool
	var yyhl8 bool = l >= 0
	yyj8++
	if yyhl8 {
		yyb8 = yyj8 > l
	} else {
		yyb8 = z.DecCheckBreak()
	}
	if yyb8 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicePtrtocurve25519_Scalar((*[]*pkg1_curve25519.Scalar)(&x.S), d)
	yyj8++
	if yyhl8 {
		yyb8 = yyj8 > l
	} else {
		yyb8 = z.DecCheckBreak()
	}
	if yyb8 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicePtrtocurve25519_Scalar((*[]*pkg1_curve25519.Scalar)(&x.R), d)
	for {
		yyj8++
		if yyhl8 {
			yyb8 = yyj8 > l
		} else {
			yyb8 = z.DecCheckBreak()
		}
		if yyb8 {
			break
		}
		z.DecReadArrayElem()
		z.DecStructFieldNotFound(yyj8-1, "")
	}
}

func (x *VerSentShares) IsCodecEmpty() bool {
	return !(len(x.S) != 0 || len(x.R) != 0 || false)
}

func (VerificationMessage) codecSelferViaCodecgen() {}
func (x *VerificationMessage) CodecEncodeSelf(e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if z.EncBasicHandle().CheckCircularRef {
		z.EncEncode(x)
		return
	}
	if x == nil {
		r.EncodeNil()
	} else {
		yy2arr2 := z.EncBasicHandle().StructToArray
		_ = yy2arr2
		const yyr2 bool = false // struct tag has 'toArray'
		var yyq2 = [3]bool{     // should field at this index be written?
			len(x.Complaints) != 0,         // C
			len(x.EncShares) != 0,          // SR
			!(x.VPComProof.IsCodecEmpty()), // V
		}
		_ = yyq2
		if yyr2 || yy2arr2 {
			z.EncWriteArrayStart(3)
			z.EncWriteArrayElem()
			if yyq2[0] {
				if x.Complaints == nil {
					r.EncodeNil()
				} else {
					z.F.EncSliceBoolV(x.Complaints, e)
				} // end block: if x.Complaints slice == nil
			} else {
				r.EncodeNil()
			}
			z.EncWriteArrayElem()
			if yyq2[1] {
				if x.EncShares == nil {
					r.EncodeNil()
				} else {
					h.encSlicecurve25519_Ciphertext(([]pkg1_curve25519.Ciphertext)(x.EncShares), e)
				} // end block: if x.EncShares slice == nil
			} else {
				r.EncodeNil()
			}
			z.EncWriteArrayElem()
			if yyq2[2] {
				yy8 := &x.VPComProof
				if yyxt9 := z.Extension(yy8); yyxt9 != nil {
					z.EncExtension(yy8, yyxt9)
				} else {
					yy8.CodecEncodeSelf(e)
				}
			} else {
				r.EncodeNil()
			}
			z.EncWriteArrayEnd()
		} else {
			var yynn2 int
			for _, b := range yyq2 {
				if b {
					yynn2++
				}
			}
			z.EncWriteMapStart(yynn2)
			yynn2 = 0
			if yyq2[0] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"C\"")
				} else {
					r.EncodeString(`C`)
				}
				z.EncWriteMapElemValue()
				if x.Complaints == nil {
					r.EncodeNil()
				} else {
					z.F.EncSliceBoolV(x.Complaints, e)
				} // end block: if x.Complaints slice == nil
			}
			if yyq2[1] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"SR\"")
				} else {
					r.EncodeString(`SR`)
				}
				z.EncWriteMapElemValue()
				if x.EncShares == nil {
					r.EncodeNil()
				} else {
					h.encSlicecurve25519_Ciphertext(([]pkg1_curve25519.Ciphertext)(x.EncShares), e)
				} // end block: if x.EncShares slice == nil
			}
			if yyq2[2] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"V\"")
				} else {
					r.EncodeString(`V`)
				}
				z.EncWriteMapElemValue()
				yy12 := &x.VPComProof
				if yyxt13 := z.Extension(yy12); yyxt13 != nil {
					z.EncExtension(yy12, yyxt13)
				} else {
					yy12.CodecEncodeSelf(e)
				}
			}
			z.EncWriteMapEnd()
		}
	}
}

func (x *VerificationMessage) CodecDecodeSelf(d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	yyct2 := r.ContainerType()
	if yyct2 == codecSelferValueTypeNil8453 {
		*(x) = VerificationMessage{}
	} else if yyct2 == codecSelferValueTypeMap8453 {
		yyl2 := z.DecReadMapStart()
		if yyl2 == 0 {
		} else {
			x.codecDecodeSelfFromMap(yyl2, d)
		}
		z.DecReadMapEnd()
	} else if yyct2 == codecSelferValueTypeArray8453 {
		yyl2 := z.DecReadArrayStart()
		if yyl2 != 0 {
			x.codecDecodeSelfFromArray(yyl2, d)
		}
		z.DecReadArrayEnd()
	} else {
		panic(errCodecSelferOnlyMapOrArrayEncodeToStruct8453)
	}
}

func (x *VerificationMessage) codecDecodeSelfFromMap(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyhl3 bool = l >= 0
	for yyj3 := 0; ; yyj3++ {
		if yyhl3 {
			if yyj3 >= l {
				break
			}
		} else {
			if z.DecCheckBreak() {
				break
			}
		}
		z.DecReadMapElemKey()
		yys3 := r.DecodeStringAsBytes()
		z.DecReadMapElemValue()
		switch string(yys3) {
		case "C":
			z.F.DecSliceBoolX(&x.Complaints, d)
		case "SR":
			h.decSlicecurve25519_Ciphertext((*[]pkg1_curve25519.Ciphertext)(&x.EncShares), d)
		case "V":
			if yyxt9 := z.Extension(x.VPComProof); yyxt9 != nil {
				z.DecExtension(&x.VPComProof, yyxt9)
			} else {
				x.VPComProof.CodecDecodeSelf(d)
			}
		default:
			z.DecStructFieldNotFound(-1, string(yys3))
		} // end switch yys3
	} // end for yyj3
}

func (x *VerificationMessage) codecDecodeSelfFromArray(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyj10 int
	var yyb10 bool
	var yyhl10 bool = l >= 0
	yyj10++
	if yyhl10 {
		yyb10 = yyj10 > l
	} else {
		yyb10 = z.DecCheckBreak()
	}
	if yyb10 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	z.F.DecSliceBoolX(&x.Complaints, d)
	yyj10++
	if yyhl10 {
		yyb10 = yyj10 > l
	} else {
		yyb10 = z.DecCheckBreak()
	}
	if yyb10 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_Ciphertext((*[]pkg1_curve25519.Ciphertext)(&x.EncShares), d)
	yyj10++
	if yyhl10 {
		yyb10 = yyj10 > l
	} else {
		yyb10 = z.DecCheckBreak()
	}
	if yyb10 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	if yyxt16 := z.Extension(x.VPComProof); yyxt16 != nil {
		z.DecExtension(&x.VPComProof, yyxt16)
	} else {
		x.VPComProof.CodecDecodeSelf(d)
	}
	for {
		yyj10++
		if yyhl10 {
			yyb10 = yyj10 > l
		} else {
			yyb10 = z.DecCheckBreak()
		}
		if yyb10 {
			break
		}
		z.DecReadArrayElem()
		z.DecStructFieldNotFound(yyj10-1, "")
	}
}

func (x *VerificationMessage) IsCodecEmpty() bool {
	return !(len(x.Complaints) != 0 || len(x.EncShares) != 0 || !(x.VPComProof.IsCodecEmpty()) || false)
}

func (PairIJ) codecSelferViaCodecgen() {}
func (x *PairIJ) CodecEncodeSelf(e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if z.EncBasicHandle().CheckCircularRef {
		z.EncEncode(x)
		return
	}
	if x == nil {
		r.EncodeNil()
	} else {
		yy2arr2 := z.EncBasicHandle().StructToArray
		_ = yy2arr2
		const yyr2 bool = false // struct tag has 'toArray'
		if yyr2 || yy2arr2 {
			z.EncWriteArrayStart(0)
			z.EncWriteArrayEnd()
		} else {
			z.EncWriteMapStart(0)
			z.EncWriteMapEnd()
		}
	}
}

func (x *PairIJ) CodecDecodeSelf(d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	yyct2 := r.ContainerType()
	if yyct2 == codecSelferValueTypeNil8453 {
		*(x) = PairIJ{}
	} else if yyct2 == codecSelferValueTypeMap8453 {
		yyl2 := z.DecReadMapStart()
		if yyl2 == 0 {
		} else {
			x.codecDecodeSelfFromMap(yyl2, d)
		}
		z.DecReadMapEnd()
	} else if yyct2 == codecSelferValueTypeArray8453 {
		yyl2 := z.DecReadArrayStart()
		if yyl2 != 0 {
			x.codecDecodeSelfFromArray(yyl2, d)
		}
		z.DecReadArrayEnd()
	} else {
		panic(errCodecSelferOnlyMapOrArrayEncodeToStruct8453)
	}
}

func (x *PairIJ) codecDecodeSelfFromMap(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyhl3 bool = l >= 0
	for yyj3 := 0; ; yyj3++ {
		if yyhl3 {
			if yyj3 >= l {
				break
			}
		} else {
			if z.DecCheckBreak() {
				break
			}
		}
		z.DecReadMapElemKey()
		yys3 := r.DecodeStringAsBytes()
		z.DecReadMapElemValue()
		switch string(yys3) {
		default:
			z.DecStructFieldNotFound(-1, string(yys3))
		} // end switch yys3
	} // end for yyj3
}

func (x *PairIJ) codecDecodeSelfFromArray(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyj4 int
	var yyb4 bool
	var yyhl4 bool = l >= 0
	for {
		yyj4++
		if yyhl4 {
			yyb4 = yyj4 > l
		} else {
			yyb4 = z.DecCheckBreak()
		}
		if yyb4 {
			break
		}
		z.DecReadArrayElem()
		z.DecStructFieldNotFound(yyj4-1, "")
	}
}

func (x *PairIJ) IsCodecEmpty() bool {
	return !(false)
}

func (ResolutionMessage) codecSelferViaCodecgen() {}
func (x *ResolutionMessage) CodecEncodeSelf(e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if z.EncBasicHandle().CheckCircularRef {
		z.EncEncode(x)
		return
	}
	if x == nil {
		r.EncodeNil()
	} else {
		yy2arr2 := z.EncBasicHandle().StructToArray
		_ = yy2arr2
		const yyr2 bool = false // struct tag has 'toArray'
		var yyq2 = [1]bool{     // should field at this index be written?
			len(x.EpsShares) != 0, // E
		}
		_ = yyq2
		if yyr2 || yy2arr2 {
			z.EncWriteArrayStart(1)
			z.EncWriteArrayElem()
			if yyq2[0] {
				if x.EpsShares == nil {
					r.EncodeNil()
				} else {
					h.encMapPairIJcurve25519_Scalar((map[PairIJ]pkg1_curve25519.Scalar)(x.EpsShares), e)
				} // end block: if x.EpsShares map == nil
			} else {
				r.EncodeNil()
			}
			z.EncWriteArrayEnd()
		} else {
			var yynn2 int
			for _, b := range yyq2 {
				if b {
					yynn2++
				}
			}
			z.EncWriteMapStart(yynn2)
			yynn2 = 0
			if yyq2[0] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"E\"")
				} else {
					r.EncodeString(`E`)
				}
				z.EncWriteMapElemValue()
				if x.EpsShares == nil {
					r.EncodeNil()
				} else {
					h.encMapPairIJcurve25519_Scalar((map[PairIJ]pkg1_curve25519.Scalar)(x.EpsShares), e)
				} // end block: if x.EpsShares map == nil
			}
			z.EncWriteMapEnd()
		}
	}
}

func (x *ResolutionMessage) CodecDecodeSelf(d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	yyct2 := r.ContainerType()
	if yyct2 == codecSelferValueTypeNil8453 {
		*(x) = ResolutionMessage{}
	} else if yyct2 == codecSelferValueTypeMap8453 {
		yyl2 := z.DecReadMapStart()
		if yyl2 == 0 {
		} else {
			x.codecDecodeSelfFromMap(yyl2, d)
		}
		z.DecReadMapEnd()
	} else if yyct2 == codecSelferValueTypeArray8453 {
		yyl2 := z.DecReadArrayStart()
		if yyl2 != 0 {
			x.codecDecodeSelfFromArray(yyl2, d)
		}
		z.DecReadArrayEnd()
	} else {
		panic(errCodecSelferOnlyMapOrArrayEncodeToStruct8453)
	}
}

func (x *ResolutionMessage) codecDecodeSelfFromMap(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyhl3 bool = l >= 0
	for yyj3 := 0; ; yyj3++ {
		if yyhl3 {
			if yyj3 >= l {
				break
			}
		} else {
			if z.DecCheckBreak() {
				break
			}
		}
		z.DecReadMapElemKey()
		yys3 := r.DecodeStringAsBytes()
		z.DecReadMapElemValue()
		switch string(yys3) {
		case "E":
			h.decMapPairIJcurve25519_Scalar((*map[PairIJ]pkg1_curve25519.Scalar)(&x.EpsShares), d)
		default:
			z.DecStructFieldNotFound(-1, string(yys3))
		} // end switch yys3
	} // end for yyj3
}

func (x *ResolutionMessage) codecDecodeSelfFromArray(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyj6 int
	var yyb6 bool
	var yyhl6 bool = l >= 0
	yyj6++
	if yyhl6 {
		yyb6 = yyj6 > l
	} else {
		yyb6 = z.DecCheckBreak()
	}
	if yyb6 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decMapPairIJcurve25519_Scalar((*map[PairIJ]pkg1_curve25519.Scalar)(&x.EpsShares), d)
	for {
		yyj6++
		if yyhl6 {
			yyb6 = yyj6 > l
		} else {
			yyb6 = z.DecCheckBreak()
		}
		if yyb6 {
			break
		}
		z.DecReadArrayElem()
		z.DecStructFieldNotFound(yyj6-1, "")
	}
}

func (x *ResolutionMessage) IsCodecEmpty() bool {
	return !(len(x.EpsShares) != 0 || false)
}

func (TripleIJL) codecSelferViaCodecgen() {}
func (x *TripleIJL) CodecEncodeSelf(e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if z.EncBasicHandle().CheckCircularRef {
		z.EncEncode(x)
		return
	}
	if x == nil {
		r.EncodeNil()
	} else {
		yy2arr2 := z.EncBasicHandle().StructToArray
		_ = yy2arr2
		const yyr2 bool = false // struct tag has 'toArray'
		if yyr2 || yy2arr2 {
			z.EncWriteArrayStart(0)
			z.EncWriteArrayEnd()
		} else {
			z.EncWriteMapStart(0)
			z.EncWriteMapEnd()
		}
	}
}

func (x *TripleIJL) CodecDecodeSelf(d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	yyct2 := r.ContainerType()
	if yyct2 == codecSelferValueTypeNil8453 {
		*(x) = TripleIJL{}
	} else if yyct2 == codecSelferValueTypeMap8453 {
		yyl2 := z.DecReadMapStart()
		if yyl2 == 0 {
		} else {
			x.codecDecodeSelfFromMap(yyl2, d)
		}
		z.DecReadMapEnd()
	} else if yyct2 == codecSelferValueTypeArray8453 {
		yyl2 := z.DecReadArrayStart()
		if yyl2 != 0 {
			x.codecDecodeSelfFromArray(yyl2, d)
		}
		z.DecReadArrayEnd()
	} else {
		panic(errCodecSelferOnlyMapOrArrayEncodeToStruct8453)
	}
}

func (x *TripleIJL) codecDecodeSelfFromMap(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyhl3 bool = l >= 0
	for yyj3 := 0; ; yyj3++ {
		if yyhl3 {
			if yyj3 >= l {
				break
			}
		} else {
			if z.DecCheckBreak() {
				break
			}
		}
		z.DecReadMapElemKey()
		yys3 := r.DecodeStringAsBytes()
		z.DecReadMapElemValue()
		switch string(yys3) {
		default:
			z.DecStructFieldNotFound(-1, string(yys3))
		} // end switch yys3
	} // end for yyj3
}

func (x *TripleIJL) codecDecodeSelfFromArray(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyj4 int
	var yyb4 bool
	var yyhl4 bool = l >= 0
	for {
		yyj4++
		if yyhl4 {
			yyb4 = yyj4 > l
		} else {
			yyb4 = z.DecCheckBreak()
		}
		if yyb4 {
			break
		}
		z.DecReadArrayElem()
		z.DecStructFieldNotFound(yyj4-1, "")
	}
}

func (x *TripleIJL) IsCodecEmpty() bool {
	return !(false)
}

func (VPCommitProof) codecSelferViaCodecgen() {}
func (x *VPCommitProof) CodecEncodeSelf(e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if z.EncBasicHandle().CheckCircularRef {
		z.EncEncode(x)
		return
	}
	if x == nil {
		r.EncodeNil()
	} else {
		yy2arr2 := z.EncBasicHandle().StructToArray
		_ = yy2arr2
		const yyr2 bool = false // struct tag has 'toArray'
		if yyr2 || yy2arr2 {
			z.EncWriteArrayStart(3)
			z.EncWriteArrayElem()
			if x.ComR == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.ComR), e)
			} // end block: if x.ComR slice == nil
			z.EncWriteArrayElem()
			yy7 := &x.DLProofR
			if yyxt8 := z.Extension(yy7); yyxt8 != nil {
				z.EncExtension(yy7, yyxt8)
			} else {
				yy7.CodecEncodeSelf(e)
			}
			z.EncWriteArrayElem()
			if x.HashL == nil {
				r.EncodeNil()
			} else {
				h.encSliceArray32uint8(([][32]uint8)(x.HashL), e)
			} // end block: if x.HashL slice == nil
			z.EncWriteArrayEnd()
		} else {
			z.EncWriteMapStart(3)
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"c\"")
			} else {
				r.EncodeString(`c`)
			}
			z.EncWriteMapElemValue()
			if x.ComR == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_PointXY(([]pkg1_curve25519.PointXY)(x.ComR), e)
			} // end block: if x.ComR slice == nil
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"p\"")
			} else {
				r.EncodeString(`p`)
			}
			z.EncWriteMapElemValue()
			yy11 := &x.DLProofR
			if yyxt12 := z.Extension(yy11); yyxt12 != nil {
				z.EncExtension(yy11, yyxt12)
			} else {
				yy11.CodecEncodeSelf(e)
			}
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"h\"")
			} else {
				r.EncodeString(`h`)
			}
			z.EncWriteMapElemValue()
			if x.HashL == nil {
				r.EncodeNil()
			} else {
				h.encSliceArray32uint8(([][32]uint8)(x.HashL), e)
			} // end block: if x.HashL slice == nil
			z.EncWriteMapEnd()
		}
	}
}

func (x *VPCommitProof) CodecDecodeSelf(d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	yyct2 := r.ContainerType()
	if yyct2 == codecSelferValueTypeNil8453 {
		*(x) = VPCommitProof{}
	} else if yyct2 == codecSelferValueTypeMap8453 {
		yyl2 := z.DecReadMapStart()
		if yyl2 == 0 {
		} else {
			x.codecDecodeSelfFromMap(yyl2, d)
		}
		z.DecReadMapEnd()
	} else if yyct2 == codecSelferValueTypeArray8453 {
		yyl2 := z.DecReadArrayStart()
		if yyl2 != 0 {
			x.codecDecodeSelfFromArray(yyl2, d)
		}
		z.DecReadArrayEnd()
	} else {
		panic(errCodecSelferOnlyMapOrArrayEncodeToStruct8453)
	}
}

func (x *VPCommitProof) codecDecodeSelfFromMap(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyhl3 bool = l >= 0
	for yyj3 := 0; ; yyj3++ {
		if yyhl3 {
			if yyj3 >= l {
				break
			}
		} else {
			if z.DecCheckBreak() {
				break
			}
		}
		z.DecReadMapElemKey()
		yys3 := r.DecodeStringAsBytes()
		z.DecReadMapElemValue()
		switch string(yys3) {
		case "c":
			h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.ComR), d)
		case "p":
			if yyxt7 := z.Extension(x.DLProofR); yyxt7 != nil {
				z.DecExtension(&x.DLProofR, yyxt7)
			} else {
				x.DLProofR.CodecDecodeSelf(d)
			}
		case "h":
			h.decSliceArray32uint8((*[][32]uint8)(&x.HashL), d)
		default:
			z.DecStructFieldNotFound(-1, string(yys3))
		} // end switch yys3
	} // end for yyj3
}

func (x *VPCommitProof) codecDecodeSelfFromArray(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyj10 int
	var yyb10 bool
	var yyhl10 bool = l >= 0
	yyj10++
	if yyhl10 {
		yyb10 = yyj10 > l
	} else {
		yyb10 = z.DecCheckBreak()
	}
	if yyb10 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_PointXY((*[]pkg1_curve25519.PointXY)(&x.ComR), d)
	yyj10++
	if yyhl10 {
		yyb10 = yyj10 > l
	} else {
		yyb10 = z.DecCheckBreak()
	}
	if yyb10 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	if yyxt14 := z.Extension(x.DLProofR); yyxt14 != nil {
		z.DecExtension(&x.DLProofR, yyxt14)
	} else {
		x.DLProofR.CodecDecodeSelf(d)
	}
	yyj10++
	if yyhl10 {
		yyb10 = yyj10 > l
	} else {
		yyb10 = z.DecCheckBreak()
	}
	if yyb10 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSliceArray32uint8((*[][32]uint8)(&x.HashL), d)
	for {
		yyj10++
		if yyhl10 {
			yyb10 = yyj10 > l
		} else {
			yyb10 = z.DecCheckBreak()
		}
		if yyb10 {
			break
		}
		z.DecReadArrayElem()
		z.DecStructFieldNotFound(yyj10-1, "")
	}
}

func (x *VPCommitProof) IsCodecEmpty() bool {
	return !(len(x.ComR) != 0 || !(x.DLProofR.IsCodecEmpty()) || len(x.HashL) != 0 || false)
}

func (VPHashLIn) codecSelferViaCodecgen() {}
func (x *VPHashLIn) CodecEncodeSelf(e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if z.EncBasicHandle().CheckCircularRef {
		z.EncEncode(x)
		return
	}
	if x == nil {
		r.EncodeNil()
	} else {
		yy2arr2 := z.EncBasicHandle().StructToArray
		_ = yy2arr2
		const yyr2 bool = false // struct tag has 'toArray'
		if yyr2 || yy2arr2 {
			z.EncWriteArrayStart(1)
			z.EncWriteArrayElem()
			if x.SigmaL == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_Scalar(([]pkg1_curve25519.Scalar)(x.SigmaL), e)
			} // end block: if x.SigmaL slice == nil
			z.EncWriteArrayEnd()
		} else {
			z.EncWriteMapStart(1)
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"s\"")
			} else {
				r.EncodeString(`s`)
			}
			z.EncWriteMapElemValue()
			if x.SigmaL == nil {
				r.EncodeNil()
			} else {
				h.encSlicecurve25519_Scalar(([]pkg1_curve25519.Scalar)(x.SigmaL), e)
			} // end block: if x.SigmaL slice == nil
			z.EncWriteMapEnd()
		}
	}
}

func (x *VPHashLIn) CodecDecodeSelf(d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	yyct2 := r.ContainerType()
	if yyct2 == codecSelferValueTypeNil8453 {
		*(x) = VPHashLIn{}
	} else if yyct2 == codecSelferValueTypeMap8453 {
		yyl2 := z.DecReadMapStart()
		if yyl2 == 0 {
		} else {
			x.codecDecodeSelfFromMap(yyl2, d)
		}
		z.DecReadMapEnd()
	} else if yyct2 == codecSelferValueTypeArray8453 {
		yyl2 := z.DecReadArrayStart()
		if yyl2 != 0 {
			x.codecDecodeSelfFromArray(yyl2, d)
		}
		z.DecReadArrayEnd()
	} else {
		panic(errCodecSelferOnlyMapOrArrayEncodeToStruct8453)
	}
}

func (x *VPHashLIn) codecDecodeSelfFromMap(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyhl3 bool = l >= 0
	for yyj3 := 0; ; yyj3++ {
		if yyhl3 {
			if yyj3 >= l {
				break
			}
		} else {
			if z.DecCheckBreak() {
				break
			}
		}
		z.DecReadMapElemKey()
		yys3 := r.DecodeStringAsBytes()
		z.DecReadMapElemValue()
		switch string(yys3) {
		case "s":
			h.decSlicecurve25519_Scalar((*[]pkg1_curve25519.Scalar)(&x.SigmaL), d)
		default:
			z.DecStructFieldNotFound(-1, string(yys3))
		} // end switch yys3
	} // end for yyj3
}

func (x *VPHashLIn) codecDecodeSelfFromArray(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyj6 int
	var yyb6 bool
	var yyhl6 bool = l >= 0
	yyj6++
	if yyhl6 {
		yyb6 = yyj6 > l
	} else {
		yyb6 = z.DecCheckBreak()
	}
	if yyb6 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSlicecurve25519_Scalar((*[]pkg1_curve25519.Scalar)(&x.SigmaL), d)
	for {
		yyj6++
		if yyhl6 {
			yyb6 = yyj6 > l
		} else {
			yyb6 = z.DecCheckBreak()
		}
		if yyb6 {
			break
		}
		z.DecReadArrayElem()
		z.DecStructFieldNotFound(yyj6-1, "")
	}
}

func (x *VPHashLIn) IsCodecEmpty() bool {
	return !(len(x.SigmaL) != 0 || false)
}

func (VPHashEIn) codecSelferViaCodecgen() {}
func (x *VPHashEIn) CodecEncodeSelf(e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if z.EncBasicHandle().CheckCircularRef {
		z.EncEncode(x)
		return
	}
	if x == nil {
		r.EncodeNil()
	} else {
		yy2arr2 := z.EncBasicHandle().StructToArray
		_ = yy2arr2
		const yyr2 bool = false // struct tag has 'toArray'
		if yyr2 || yy2arr2 {
			z.EncWriteArrayStart(1)
			z.EncWriteArrayElem()
			if x.HashL == nil {
				r.EncodeNil()
			} else {
				h.encSliceArray32uint8(([][32]uint8)(x.HashL), e)
			} // end block: if x.HashL slice == nil
			z.EncWriteArrayEnd()
		} else {
			z.EncWriteMapStart(1)
			z.EncWriteMapElemKey()
			if z.IsJSONHandle() {
				z.WriteStr("\"h\"")
			} else {
				r.EncodeString(`h`)
			}
			z.EncWriteMapElemValue()
			if x.HashL == nil {
				r.EncodeNil()
			} else {
				h.encSliceArray32uint8(([][32]uint8)(x.HashL), e)
			} // end block: if x.HashL slice == nil
			z.EncWriteMapEnd()
		}
	}
}

func (x *VPHashEIn) CodecDecodeSelf(d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	yyct2 := r.ContainerType()
	if yyct2 == codecSelferValueTypeNil8453 {
		*(x) = VPHashEIn{}
	} else if yyct2 == codecSelferValueTypeMap8453 {
		yyl2 := z.DecReadMapStart()
		if yyl2 == 0 {
		} else {
			x.codecDecodeSelfFromMap(yyl2, d)
		}
		z.DecReadMapEnd()
	} else if yyct2 == codecSelferValueTypeArray8453 {
		yyl2 := z.DecReadArrayStart()
		if yyl2 != 0 {
			x.codecDecodeSelfFromArray(yyl2, d)
		}
		z.DecReadArrayEnd()
	} else {
		panic(errCodecSelferOnlyMapOrArrayEncodeToStruct8453)
	}
}

func (x *VPHashEIn) codecDecodeSelfFromMap(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyhl3 bool = l >= 0
	for yyj3 := 0; ; yyj3++ {
		if yyhl3 {
			if yyj3 >= l {
				break
			}
		} else {
			if z.DecCheckBreak() {
				break
			}
		}
		z.DecReadMapElemKey()
		yys3 := r.DecodeStringAsBytes()
		z.DecReadMapElemValue()
		switch string(yys3) {
		case "h":
			h.decSliceArray32uint8((*[][32]uint8)(&x.HashL), d)
		default:
			z.DecStructFieldNotFound(-1, string(yys3))
		} // end switch yys3
	} // end for yyj3
}

func (x *VPHashEIn) codecDecodeSelfFromArray(l int, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyj6 int
	var yyb6 bool
	var yyhl6 bool = l >= 0
	yyj6++
	if yyhl6 {
		yyb6 = yyj6 > l
	} else {
		yyb6 = z.DecCheckBreak()
	}
	if yyb6 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSliceArray32uint8((*[][32]uint8)(&x.HashL), d)
	for {
		yyj6++
		if yyhl6 {
			yyb6 = yyj6 > l
		} else {
			yyb6 = z.DecCheckBreak()
		}
		if yyb6 {
			break
		}
		z.DecReadArrayElem()
		z.DecStructFieldNotFound(yyj6-1, "")
	}
}

func (x *VPHashEIn) IsCodecEmpty() bool {
	return !(len(x.HashL) != 0 || false)
}

func (x codecSelfer8453) encSlicecurve25519_PointXY(v []pkg1_curve25519.PointXY, e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if v == nil {
		r.EncodeNil()
		return
	}
	z.EncWriteArrayStart(len(v))
	for yyv1 := range v {
		z.EncWriteArrayElem()
		yy2 := &v[yyv1]
		if yyxt3 := z.Extension(yy2); yyxt3 != nil {
			z.EncExtension(yy2, yyxt3)
		} else {
			z.F.EncSliceUint8V(([]uint8)(yy2[:]), e)
		}
	}
	z.EncWriteArrayEnd()
}

func (x codecSelfer8453) decSlicecurve25519_PointXY(v *[]pkg1_curve25519.PointXY, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r

	yyv1 := *v
	yyh1, yyl1 := z.DecSliceHelperStart()
	var yyc1 bool
	_ = yyc1
	if yyh1.IsNil {
		if yyv1 != nil {
			yyv1 = nil
			yyc1 = true
		}
	} else if yyl1 == 0 {
		if yyv1 == nil {
			yyv1 = []pkg1_curve25519.PointXY{}
			yyc1 = true
		} else if len(yyv1) != 0 {
			yyv1 = yyv1[:0]
			yyc1 = true
		}
	} else {
		yyhl1 := yyl1 > 0
		var yyrl1 int
		_ = yyrl1
		if yyhl1 {
			if yyl1 > cap(yyv1) {
				yyrl1 = z.DecInferLen(yyl1, z.DecBasicHandle().MaxInitLen, 64)
				if yyrl1 <= cap(yyv1) {
					yyv1 = yyv1[:yyrl1]
				} else {
					yyv1 = make([]pkg1_curve25519.PointXY, yyrl1)
				}
				yyc1 = true
			} else if yyl1 != len(yyv1) {
				yyv1 = yyv1[:yyl1]
				yyc1 = true
			}
		}
		var yyj1 int
		for yyj1 = 0; (yyhl1 && yyj1 < yyl1) || !(yyhl1 || z.DecCheckBreak()); yyj1++ { // bounds-check-elimination
			if yyj1 == 0 && yyv1 == nil {
				if yyhl1 {
					yyrl1 = z.DecInferLen(yyl1, z.DecBasicHandle().MaxInitLen, 64)
				} else {
					yyrl1 = 8
				}
				yyv1 = make([]pkg1_curve25519.PointXY, yyrl1)
				yyc1 = true
			}
			yyh1.ElemContainerState(yyj1)
			var yydb1 bool
			if yyj1 >= len(yyv1) {
				yyv1 = append(yyv1, pkg1_curve25519.PointXY{})
				yyc1 = true
			}
			if yydb1 {
				z.DecSwallow()
			} else {
				if yyxt3 := z.Extension(yyv1[yyj1]); yyxt3 != nil {
					z.DecExtension(&yyv1[yyj1], yyxt3)
				} else {
					z.F.DecSliceUint8N(([]uint8)(yyv1[yyj1][:]), d)
				}
			}
		}
		if yyj1 < len(yyv1) {
			yyv1 = yyv1[:yyj1]
			yyc1 = true
		} else if yyj1 == 0 && yyv1 == nil {
			yyv1 = make([]pkg1_curve25519.PointXY, 0)
			yyc1 = true
		}
	}
	yyh1.End()
	if yyc1 {
		*v = yyv1
	}
}

func (x codecSelfer8453) encSlicecurve25519_Scalar(v []pkg1_curve25519.Scalar, e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if v == nil {
		r.EncodeNil()
		return
	}
	z.EncWriteArrayStart(len(v))
	for yyv1 := range v {
		z.EncWriteArrayElem()
		yy2 := &v[yyv1]
		if yyxt3 := z.Extension(yy2); yyxt3 != nil {
			z.EncExtension(yy2, yyxt3)
		} else {
			z.F.EncSliceUint8V(([]uint8)(yy2[:]), e)
		}
	}
	z.EncWriteArrayEnd()
}

func (x codecSelfer8453) decSlicecurve25519_Scalar(v *[]pkg1_curve25519.Scalar, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r

	yyv1 := *v
	yyh1, yyl1 := z.DecSliceHelperStart()
	var yyc1 bool
	_ = yyc1
	if yyh1.IsNil {
		if yyv1 != nil {
			yyv1 = nil
			yyc1 = true
		}
	} else if yyl1 == 0 {
		if yyv1 == nil {
			yyv1 = []pkg1_curve25519.Scalar{}
			yyc1 = true
		} else if len(yyv1) != 0 {
			yyv1 = yyv1[:0]
			yyc1 = true
		}
	} else {
		yyhl1 := yyl1 > 0
		var yyrl1 int
		_ = yyrl1
		if yyhl1 {
			if yyl1 > cap(yyv1) {
				yyrl1 = z.DecInferLen(yyl1, z.DecBasicHandle().MaxInitLen, 32)
				if yyrl1 <= cap(yyv1) {
					yyv1 = yyv1[:yyrl1]
				} else {
					yyv1 = make([]pkg1_curve25519.Scalar, yyrl1)
				}
				yyc1 = true
			} else if yyl1 != len(yyv1) {
				yyv1 = yyv1[:yyl1]
				yyc1 = true
			}
		}
		var yyj1 int
		for yyj1 = 0; (yyhl1 && yyj1 < yyl1) || !(yyhl1 || z.DecCheckBreak()); yyj1++ { // bounds-check-elimination
			if yyj1 == 0 && yyv1 == nil {
				if yyhl1 {
					yyrl1 = z.DecInferLen(yyl1, z.DecBasicHandle().MaxInitLen, 32)
				} else {
					yyrl1 = 8
				}
				yyv1 = make([]pkg1_curve25519.Scalar, yyrl1)
				yyc1 = true
			}
			yyh1.ElemContainerState(yyj1)
			var yydb1 bool
			if yyj1 >= len(yyv1) {
				yyv1 = append(yyv1, pkg1_curve25519.Scalar{})
				yyc1 = true
			}
			if yydb1 {
				z.DecSwallow()
			} else {
				if yyxt3 := z.Extension(yyv1[yyj1]); yyxt3 != nil {
					z.DecExtension(&yyv1[yyj1], yyxt3)
				} else {
					z.F.DecSliceUint8N(([]uint8)(yyv1[yyj1][:]), d)
				}
			}
		}
		if yyj1 < len(yyv1) {
			yyv1 = yyv1[:yyj1]
			yyc1 = true
		} else if yyj1 == 0 && yyv1 == nil {
			yyv1 = make([]pkg1_curve25519.Scalar, 0)
			yyc1 = true
		}
	}
	yyh1.End()
	if yyc1 {
		*v = yyv1
	}
}

func (x codecSelfer8453) encSlicecurve25519_Ciphertext(v []pkg1_curve25519.Ciphertext, e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if v == nil {
		r.EncodeNil()
		return
	}
	z.EncWriteArrayStart(len(v))
	for yyv1 := range v {
		z.EncWriteArrayElem()
		if yyxt2 := z.Extension(v[yyv1]); yyxt2 != nil {
			z.EncExtension(v[yyv1], yyxt2)
		} else {
			if v[yyv1] == nil {
				r.EncodeNil()
			} else {
				z.F.EncSliceUint8V(([]uint8)(v[yyv1]), e)
			} // end block: if v[yyv1] slice == nil
		}
	}
	z.EncWriteArrayEnd()
}

func (x codecSelfer8453) decSlicecurve25519_Ciphertext(v *[]pkg1_curve25519.Ciphertext, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r

	yyv1 := *v
	yyh1, yyl1 := z.DecSliceHelperStart()
	var yyc1 bool
	_ = yyc1
	if yyh1.IsNil {
		if yyv1 != nil {
			yyv1 = nil
			yyc1 = true
		}
	} else if yyl1 == 0 {
		if yyv1 == nil {
			yyv1 = []pkg1_curve25519.Ciphertext{}
			yyc1 = true
		} else if len(yyv1) != 0 {
			yyv1 = yyv1[:0]
			yyc1 = true
		}
	} else {
		yyhl1 := yyl1 > 0
		var yyrl1 int
		_ = yyrl1
		if yyhl1 {
			if yyl1 > cap(yyv1) {
				yyrl1 = z.DecInferLen(yyl1, z.DecBasicHandle().MaxInitLen, 24)
				if yyrl1 <= cap(yyv1) {
					yyv1 = yyv1[:yyrl1]
				} else {
					yyv1 = make([]pkg1_curve25519.Ciphertext, yyrl1)
				}
				yyc1 = true
			} else if yyl1 != len(yyv1) {
				yyv1 = yyv1[:yyl1]
				yyc1 = true
			}
		}
		var yyj1 int
		for yyj1 = 0; (yyhl1 && yyj1 < yyl1) || !(yyhl1 || z.DecCheckBreak()); yyj1++ { // bounds-check-elimination
			if yyj1 == 0 && yyv1 == nil {
				if yyhl1 {
					yyrl1 = z.DecInferLen(yyl1, z.DecBasicHandle().MaxInitLen, 24)
				} else {
					yyrl1 = 8
				}
				yyv1 = make([]pkg1_curve25519.Ciphertext, yyrl1)
				yyc1 = true
			}
			yyh1.ElemContainerState(yyj1)
			var yydb1 bool
			if yyj1 >= len(yyv1) {
				yyv1 = append(yyv1, nil)
				yyc1 = true
			}
			if yydb1 {
				z.DecSwallow()
			} else {
				if yyxt3 := z.Extension(yyv1[yyj1]); yyxt3 != nil {
					z.DecExtension(&yyv1[yyj1], yyxt3)
				} else {
					z.F.DecSliceUint8X((*[]uint8)(&yyv1[yyj1]), d)
				}
			}
		}
		if yyj1 < len(yyv1) {
			yyv1 = yyv1[:yyj1]
			yyc1 = true
		} else if yyj1 == 0 && yyv1 == nil {
			yyv1 = make([]pkg1_curve25519.Ciphertext, 0)
			yyc1 = true
		}
	}
	yyh1.End()
	if yyc1 {
		*v = yyv1
	}
}

func (x codecSelfer8453) encSlicecurve25519_SymmetricCiphertext(v []pkg1_curve25519.SymmetricCiphertext, e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if v == nil {
		r.EncodeNil()
		return
	}
	z.EncWriteArrayStart(len(v))
	for yyv1 := range v {
		z.EncWriteArrayElem()
		if yyxt2 := z.Extension(v[yyv1]); yyxt2 != nil {
			z.EncExtension(v[yyv1], yyxt2)
		} else {
			if v[yyv1] == nil {
				r.EncodeNil()
			} else {
				z.F.EncSliceUint8V(([]uint8)(v[yyv1]), e)
			} // end block: if v[yyv1] slice == nil
		}
	}
	z.EncWriteArrayEnd()
}

func (x codecSelfer8453) decSlicecurve25519_SymmetricCiphertext(v *[]pkg1_curve25519.SymmetricCiphertext, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r

	yyv1 := *v
	yyh1, yyl1 := z.DecSliceHelperStart()
	var yyc1 bool
	_ = yyc1
	if yyh1.IsNil {
		if yyv1 != nil {
			yyv1 = nil
			yyc1 = true
		}
	} else if yyl1 == 0 {
		if yyv1 == nil {
			yyv1 = []pkg1_curve25519.SymmetricCiphertext{}
			yyc1 = true
		} else if len(yyv1) != 0 {
			yyv1 = yyv1[:0]
			yyc1 = true
		}
	} else {
		yyhl1 := yyl1 > 0
		var yyrl1 int
		_ = yyrl1
		if yyhl1 {
			if yyl1 > cap(yyv1) {
				yyrl1 = z.DecInferLen(yyl1, z.DecBasicHandle().MaxInitLen, 24)
				if yyrl1 <= cap(yyv1) {
					yyv1 = yyv1[:yyrl1]
				} else {
					yyv1 = make([]pkg1_curve25519.SymmetricCiphertext, yyrl1)
				}
				yyc1 = true
			} else if yyl1 != len(yyv1) {
				yyv1 = yyv1[:yyl1]
				yyc1 = true
			}
		}
		var yyj1 int
		for yyj1 = 0; (yyhl1 && yyj1 < yyl1) || !(yyhl1 || z.DecCheckBreak()); yyj1++ { // bounds-check-elimination
			if yyj1 == 0 && yyv1 == nil {
				if yyhl1 {
					yyrl1 = z.DecInferLen(yyl1, z.DecBasicHandle().MaxInitLen, 24)
				} else {
					yyrl1 = 8
				}
				yyv1 = make([]pkg1_curve25519.SymmetricCiphertext, yyrl1)
				yyc1 = true
			}
			yyh1.ElemContainerState(yyj1)
			var yydb1 bool
			if yyj1 >= len(yyv1) {
				yyv1 = append(yyv1, nil)
				yyc1 = true
			}
			if yydb1 {
				z.DecSwallow()
			} else {
				if yyxt3 := z.Extension(yyv1[yyj1]); yyxt3 != nil {
					z.DecExtension(&yyv1[yyj1], yyxt3)
				} else {
					z.F.DecSliceUint8X((*[]uint8)(&yyv1[yyj1]), d)
				}
			}
		}
		if yyj1 < len(yyv1) {
			yyv1 = yyv1[:yyj1]
			yyc1 = true
		} else if yyj1 == 0 && yyv1 == nil {
			yyv1 = make([]pkg1_curve25519.SymmetricCiphertext, 0)
			yyc1 = true
		}
	}
	yyh1.End()
	if yyc1 {
		*v = yyv1
	}
}

func (x codecSelfer8453) encSliceSliceArray32uint8(v [][][32]uint8, e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if v == nil {
		r.EncodeNil()
		return
	}
	z.EncWriteArrayStart(len(v))
	for yyv1 := range v {
		z.EncWriteArrayElem()
		if v[yyv1] == nil {
			r.EncodeNil()
		} else {
			h.encSliceArray32uint8(([][32]uint8)(v[yyv1]), e)
		} // end block: if v[yyv1] slice == nil
	}
	z.EncWriteArrayEnd()
}

func (x codecSelfer8453) decSliceSliceArray32uint8(v *[][][32]uint8, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r

	yyv1 := *v
	yyh1, yyl1 := z.DecSliceHelperStart()
	var yyc1 bool
	_ = yyc1
	if yyh1.IsNil {
		if yyv1 != nil {
			yyv1 = nil
			yyc1 = true
		}
	} else if yyl1 == 0 {
		if yyv1 == nil {
			yyv1 = [][][32]uint8{}
			yyc1 = true
		} else if len(yyv1) != 0 {
			yyv1 = yyv1[:0]
			yyc1 = true
		}
	} else {
		yyhl1 := yyl1 > 0
		var yyrl1 int
		_ = yyrl1
		if yyhl1 {
			if yyl1 > cap(yyv1) {
				yyrl1 = z.DecInferLen(yyl1, z.DecBasicHandle().MaxInitLen, 24)
				if yyrl1 <= cap(yyv1) {
					yyv1 = yyv1[:yyrl1]
				} else {
					yyv1 = make([][][32]uint8, yyrl1)
				}
				yyc1 = true
			} else if yyl1 != len(yyv1) {
				yyv1 = yyv1[:yyl1]
				yyc1 = true
			}
		}
		var yyj1 int
		for yyj1 = 0; (yyhl1 && yyj1 < yyl1) || !(yyhl1 || z.DecCheckBreak()); yyj1++ { // bounds-check-elimination
			if yyj1 == 0 && yyv1 == nil {
				if yyhl1 {
					yyrl1 = z.DecInferLen(yyl1, z.DecBasicHandle().MaxInitLen, 24)
				} else {
					yyrl1 = 8
				}
				yyv1 = make([][][32]uint8, yyrl1)
				yyc1 = true
			}
			yyh1.ElemContainerState(yyj1)
			var yydb1 bool
			if yyj1 >= len(yyv1) {
				yyv1 = append(yyv1, nil)
				yyc1 = true
			}
			if yydb1 {
				z.DecSwallow()
			} else {
				h.decSliceArray32uint8((*[][32]uint8)(&yyv1[yyj1]), d)
			}
		}
		if yyj1 < len(yyv1) {
			yyv1 = yyv1[:yyj1]
			yyc1 = true
		} else if yyj1 == 0 && yyv1 == nil {
			yyv1 = make([][][32]uint8, 0)
			yyc1 = true
		}
	}
	yyh1.End()
	if yyc1 {
		*v = yyv1
	}
}

func (x codecSelfer8453) encSliceArray32uint8(v [][32]uint8, e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if v == nil {
		r.EncodeNil()
		return
	}
	z.EncWriteArrayStart(len(v))
	for yyv1 := range v {
		z.EncWriteArrayElem()
		yy2 := &v[yyv1]
		h.encArray32uint8((*[32]uint8)(yy2), e)
	}
	z.EncWriteArrayEnd()
}

func (x codecSelfer8453) decSliceArray32uint8(v *[][32]uint8, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r

	yyv1 := *v
	yyh1, yyl1 := z.DecSliceHelperStart()
	var yyc1 bool
	_ = yyc1
	if yyh1.IsNil {
		if yyv1 != nil {
			yyv1 = nil
			yyc1 = true
		}
	} else if yyl1 == 0 {
		if yyv1 == nil {
			yyv1 = [][32]uint8{}
			yyc1 = true
		} else if len(yyv1) != 0 {
			yyv1 = yyv1[:0]
			yyc1 = true
		}
	} else {
		yyhl1 := yyl1 > 0
		var yyrl1 int
		_ = yyrl1
		if yyhl1 {
			if yyl1 > cap(yyv1) {
				yyrl1 = z.DecInferLen(yyl1, z.DecBasicHandle().MaxInitLen, 32)
				if yyrl1 <= cap(yyv1) {
					yyv1 = yyv1[:yyrl1]
				} else {
					yyv1 = make([][32]uint8, yyrl1)
				}
				yyc1 = true
			} else if yyl1 != len(yyv1) {
				yyv1 = yyv1[:yyl1]
				yyc1 = true
			}
		}
		var yyj1 int
		for yyj1 = 0; (yyhl1 && yyj1 < yyl1) || !(yyhl1 || z.DecCheckBreak()); yyj1++ { // bounds-check-elimination
			if yyj1 == 0 && yyv1 == nil {
				if yyhl1 {
					yyrl1 = z.DecInferLen(yyl1, z.DecBasicHandle().MaxInitLen, 32)
				} else {
					yyrl1 = 8
				}
				yyv1 = make([][32]uint8, yyrl1)
				yyc1 = true
			}
			yyh1.ElemContainerState(yyj1)
			var yydb1 bool
			if yyj1 >= len(yyv1) {
				yyv1 = append(yyv1, [32]uint8{})
				yyc1 = true
			}
			if yydb1 {
				z.DecSwallow()
			} else {
				h.decArray32uint8((*[32]uint8)(&yyv1[yyj1]), d)
			}
		}
		if yyj1 < len(yyv1) {
			yyv1 = yyv1[:yyj1]
			yyc1 = true
		} else if yyj1 == 0 && yyv1 == nil {
			yyv1 = make([][32]uint8, 0)
			yyc1 = true
		}
	}
	yyh1.End()
	if yyc1 {
		*v = yyv1
	}
}

func (x codecSelfer8453) encArray32uint8(v *[32]uint8, e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if v == nil {
		r.EncodeNil()
		return
	}
	r.EncodeStringBytesRaw(((*[32]byte)(v))[:])
}

func (x codecSelfer8453) decArray32uint8(v *[32]uint8, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	r.DecodeBytes(((*[32]byte)(v))[:])
}

func (x codecSelfer8453) encSlicePtrtocurve25519_Scalar(v []*pkg1_curve25519.Scalar, e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if v == nil {
		r.EncodeNil()
		return
	}
	z.EncWriteArrayStart(len(v))
	for yyv1 := range v {
		z.EncWriteArrayElem()
		if v[yyv1] == nil {
			r.EncodeNil()
		} else {
			if yyxt2 := z.Extension(v[yyv1]); yyxt2 != nil {
				z.EncExtension(v[yyv1], yyxt2)
			} else {
				z.F.EncSliceUint8V(([]uint8)(v[yyv1][:]), e)
			}
		}
	}
	z.EncWriteArrayEnd()
}

func (x codecSelfer8453) decSlicePtrtocurve25519_Scalar(v *[]*pkg1_curve25519.Scalar, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r

	yyv1 := *v
	yyh1, yyl1 := z.DecSliceHelperStart()
	var yyc1 bool
	_ = yyc1
	if yyh1.IsNil {
		if yyv1 != nil {
			yyv1 = nil
			yyc1 = true
		}
	} else if yyl1 == 0 {
		if yyv1 == nil {
			yyv1 = []*pkg1_curve25519.Scalar{}
			yyc1 = true
		} else if len(yyv1) != 0 {
			yyv1 = yyv1[:0]
			yyc1 = true
		}
	} else {
		yyhl1 := yyl1 > 0
		var yyrl1 int
		_ = yyrl1
		if yyhl1 {
			if yyl1 > cap(yyv1) {
				yyrl1 = z.DecInferLen(yyl1, z.DecBasicHandle().MaxInitLen, 8)
				if yyrl1 <= cap(yyv1) {
					yyv1 = yyv1[:yyrl1]
				} else {
					yyv1 = make([]*pkg1_curve25519.Scalar, yyrl1)
				}
				yyc1 = true
			} else if yyl1 != len(yyv1) {
				yyv1 = yyv1[:yyl1]
				yyc1 = true
			}
		}
		var yyj1 int
		for yyj1 = 0; (yyhl1 && yyj1 < yyl1) || !(yyhl1 || z.DecCheckBreak()); yyj1++ { // bounds-check-elimination
			if yyj1 == 0 && yyv1 == nil {
				if yyhl1 {
					yyrl1 = z.DecInferLen(yyl1, z.DecBasicHandle().MaxInitLen, 8)
				} else {
					yyrl1 = 8
				}
				yyv1 = make([]*pkg1_curve25519.Scalar, yyrl1)
				yyc1 = true
			}
			yyh1.ElemContainerState(yyj1)
			var yydb1 bool
			if yyj1 >= len(yyv1) {
				yyv1 = append(yyv1, nil)
				yyc1 = true
			}
			if yydb1 {
				z.DecSwallow()
			} else {
				if r.TryNil() {
					yyv1[yyj1] = nil
				} else {
					if yyv1[yyj1] == nil {
						yyv1[yyj1] = new(pkg1_curve25519.Scalar)
					}
					if yyxt3 := z.Extension(yyv1[yyj1]); yyxt3 != nil {
						z.DecExtension(yyv1[yyj1], yyxt3)
					} else {
						z.F.DecSliceUint8N(([]uint8)(yyv1[yyj1][:]), d)
					}
				}
			}
		}
		if yyj1 < len(yyv1) {
			yyv1 = yyv1[:yyj1]
			yyc1 = true
		} else if yyj1 == 0 && yyv1 == nil {
			yyv1 = make([]*pkg1_curve25519.Scalar, 0)
			yyc1 = true
		}
	}
	yyh1.End()
	if yyc1 {
		*v = yyv1
	}
}

func (x codecSelfer8453) encMapPairIJcurve25519_Scalar(v map[PairIJ]pkg1_curve25519.Scalar, e *codec1978.Encoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if v == nil {
		r.EncodeNil()
	} else if z.EncBasicHandle().Canonical {
		z.EncEncodeMapNonNil(v)
	} else {
		z.EncWriteMapStart(len(v))
		for yyk1, yyv1 := range v {
			z.EncWriteMapElemKey()
			yy2 := &yyk1
			if yyxt3 := z.Extension(yy2); yyxt3 != nil {
				z.EncExtension(yy2, yyxt3)
			} else {
				yy2.CodecEncodeSelf(e)
			}
			z.EncWriteMapElemValue()
			yy4 := &yyv1
			if yyxt5 := z.Extension(yy4); yyxt5 != nil {
				z.EncExtension(yy4, yyxt5)
			} else {
				z.F.EncSliceUint8V(([]uint8)(yy4[:]), e)
			}
		}
		z.EncWriteMapEnd()
	}
}

func (x codecSelfer8453) decMapPairIJcurve25519_Scalar(v *map[PairIJ]pkg1_curve25519.Scalar, d *codec1978.Decoder) {
	var h codecSelfer8453
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r

	yyv1 := *v
	yyl1 := z.DecReadMapStart()
	if yyl1 == codecSelferDecContainerLenNil8453 {
		*v = nil
	} else {
		if yyv1 == nil {
			yyrl1 := z.DecInferLen(yyl1, z.DecBasicHandle().MaxInitLen, 48)
			yyv1 = make(map[PairIJ]pkg1_curve25519.Scalar, yyrl1)
			*v = yyv1
		}
		var yymk1 PairIJ
		var yymv1 pkg1_curve25519.Scalar
		var yymg1, yymdn1 bool
		if z.DecBasicHandle().MapValueReset {
			yymg1 = true
		}
		if yyl1 != 0 {
			yyhl1 := yyl1 > 0
			for yyj1 := 0; (yyhl1 && yyj1 < yyl1) || !(yyhl1 || z.DecCheckBreak()); yyj1++ {
				z.DecReadMapElemKey()
				if yyxt3 := z.Extension(yymk1); yyxt3 != nil {
					z.DecExtension(&yymk1, yyxt3)
				} else {
					yymk1.CodecDecodeSelf(d)
				}
				if yymg1 {
					yymv1 = yyv1[yymk1]
				} else {
					yymv1 = pkg1_curve25519.Scalar{}
				}
				z.DecReadMapElemValue()
				yymdn1 = false
				if yyxt5 := z.Extension(yymv1); yyxt5 != nil {
					z.DecExtension(&yymv1, yyxt5)
				} else {
					z.F.DecSliceUint8N(([]uint8)(yymv1[:]), d)
				}
				if yymdn1 {
					yyv1[yymk1] = pkg1_curve25519.Scalar{}
				} else {
					yyv1[yymk1] = yymv1
				}
			}
		} // else len==0: leave as-is (do not clear map entries)
		z.DecReadMapEnd()
	}
}
