// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package auditor

import (
	"fmt"

	"github.com/algorand/go-algorand-sdk/encoding/msgpack"
	"github.com/shaih/go-yosovss/communication"
)

// This file is a template generating gen-matrix_generic.go

// ReceiveDealingMessages receives and parse the messages sent by dealers in the dealing round
// parties is the list of parties in the round
func ReceiveDealingMessages(bc communication.BroadcastChannel, parties []int) ([]DealingMessage, error) {
	messages := make([]DealingMessage, len(parties))

	_, bm := bc.ReceiveRound()

	for i, party := range parties {
		err := msgpack.Decode(bm[party].Payload, &messages[i])
		if err != nil {
			return nil, fmt.Errorf("decoding message from party %d (id=%d) failed: %v", i, party, err)
		}
	}

	return messages, nil
}

// This file is a template generating gen-matrix_generic.go

// ReceiveVerificationMessages receives and parse the messages sent by dealers in the dealing round
// parties is the list of parties in the round
func ReceiveVerificationMessages(bc communication.BroadcastChannel, parties []int) ([]VerificationMessage, error) {
	messages := make([]VerificationMessage, len(parties))

	_, bm := bc.ReceiveRound()

	for i, party := range parties {
		err := msgpack.Decode(bm[party].Payload, &messages[i])
		if err != nil {
			return nil, fmt.Errorf("decoding message from party %d (id=%d) failed: %v", i, party, err)
		}
	}

	return messages, nil
}

// This file is a template generating gen-matrix_generic.go

// ReceiveWitnessMessages receives and parse the messages sent by dealers in the dealing round
// parties is the list of parties in the round
func ReceiveWitnessMessages(bc communication.BroadcastChannel, parties []int) ([]WitnessMessage, error) {
	messages := make([]WitnessMessage, len(parties))

	_, bm := bc.ReceiveRound()

	for i, party := range parties {
		err := msgpack.Decode(bm[party].Payload, &messages[i])
		if err != nil {
			return nil, fmt.Errorf("decoding message from party %d (id=%d) failed: %v", i, party, err)
		}
	}

	return messages, nil
}

// This file is a template generating gen-matrix_generic.go

// ReceiveAuditingMessages receives and parse the messages sent by dealers in the dealing round
// parties is the list of parties in the round
func ReceiveAuditingMessages(bc communication.BroadcastChannel, parties []int) ([]AuditingMessage, error) {
	messages := make([]AuditingMessage, len(parties))

	_, bm := bc.ReceiveRound()

	for i, party := range parties {
		err := msgpack.Decode(bm[party].Payload, &messages[i])
		if err != nil {
			return nil, fmt.Errorf("decoding message from party %d (id=%d) failed: %v", i, party, err)
		}
	}

	return messages, nil
}
